// =============================================================================
// RaidSceneCoverageRegression [raid-scene-coverage]
//   Marker: RAID_SCENE_COVERAGE_OK / RAID_SCENE_COVERAGE_FAIL
// -----------------------------------------------------------------------------
// Assembly: DeNelle.EditorRegression (references DeNelle.Core + DeNelle.Village).
//
// WHY THIS EXISTS (WO-1732). The owner played device build 2026.09.15.370203 and
// reported, F8 seq 5245, scene RaidBase_IronBastion:
//
//     "it works on the first raid tier but on the last raid tier does destroy
//      doesnt show as destroyed can walk through."
//
// CAUSE, measured on disk 2026-09-15: RaidBaseGenerator.BuildAllRaidScenes iterated
// a HARDCODED three-id array - raider_camp_small / fortified_garrison / mage_enclave -
// and `iron_bastion` was missing from it, even though scene-configs.json authors it.
// So every content pass since re-baked three of the four raid levels and left the top
// tier frozen on an older builder:
//
//     scene                          Wall_*   Ruin_Wall_*   RuinStep
//     RaidBase_raider_camp_small        58          58          58
//     RaidBase_fortified_garrison      118         118         118
//     RaidBase_mage_enclave            158         158         158
//     RaidBase_IronBastion             210           0           0     <-- stale
//
// IronBastion still carried the pre-WO-1723 3.0 m wall partition and ZERO rubble
// objects, so WO-1723 Lane B's "one clad panel per WallSegment, rubble on collapse"
// visual never applied there. The nav bake DID cover it (RaidNavBake's exclusion is
// name-based and its list names the scene), which is precisely the owner's symptom:
// the wall stops blocking, but nothing ever looks destroyed.
//
// THE TRAP THIS GUARD CLOSES IS SPECIFICALLY THE ID/SCENE-NAME MISMATCH. The config
// id is `iron_bastion`; the scene the game loads is `RaidBase_IronBastion` - different
// casing AND separator, because WO-1705 kept the path that already existed in
// EditorBuildSettings. Naively composing `RaidBase_{id}` writes a SECOND, never-loaded
// scene and leaves the live one stale. The authored `sceneName` is the only authority:
// RaidDeployVM.cs:443 calls SceneRouter.GoRaid(_def.sceneName).
//
// The gap was even KNOWN and written down - WORK_ORDER_1632_..._RESULT.md:194 records
// "RaidBase_IronBastion.unity will NOT gain a ring from this run" - and still shipped,
// because a note in a RESULT file is not a gate. This is that gate.
//
// WHAT IT ASSERTS, for every scene-config whose authored sceneName names a RaidBase
// level (the same predicate RaidVictoryController.cs:501 uses at runtime):
//   Case 1 [exists]    the .unity file the config names is on disk.
//   Case 2 [registered] that exact path is in EditorBuildSettings and enabled - GoRaid
//                       refuses an unregistered scene.
//   Case 3 [partition]  the scene carries one Ruin_Wall_<seg> per Wall_<seg>, and more
//                       than zero - i.e. it was generated by the CURRENT clad-module
//                       partition, not an older one. This is the case that fails on the
//                       stale tree and the one that would have caught WO-1732.
//   Case 4 [bake-list]  RaidNavBake's scene list covers exactly the catalog's raid set -
//                       so the NEXT copy of this list cannot drift unnoticed either.
//                       RETIRE THIS CASE if RaidNavBake is ever changed to derive its list
//                       from the catalog the way RaidBaseGenerator now does: it reads SOURCE
//                       TEXT for literal paths, so a correctly-derived list has no literals
//                       and this case would then fail on a fix.
//   Case 5 [orphan]     no RaidBase_*.unity sits on disk unclaimed by a config - the "wrote a
//                       second scene from the ID" failure, which every case above would pass.
//
// Contract: public static bool Run(out string reason) - DataRegression-shaped, true =
// pass + one-line summary, false = fail + the offending detail. NEVER throws. Pure
// file I/O: no PlayMode, no scene load, no bake, so it is cheap enough for every gate.
//
// Standalone: run-unity-method DeNelle.Editor.Regression.RaidSceneCoverageRegression.RunAll
// =============================================================================

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using DeNelle.Village;
using UnityEngine;

namespace DeNelle.Editor.Regression
{
    public static class RaidSceneCoverageRegression
    {
        private const string ScenesDir = "Assets/Scenes";
        private const string BuildSettingsAsset = "ProjectSettings/EditorBuildSettings.asset";
        private const string NavBakeSrc = "Assets/Editor/RaidNavBake.cs";

        /// <summary>
        /// The prefix RaidBaseDresser gives a baked rubble holder: it builds
        /// <c>"Ruin_" + segName</c> (RaidBaseDresser.cs:867) where segName is the
        /// WallSegment's own name, so a <c>Wall_Outer_SN_3</c> yields
        /// <c>Ruin_Wall_Outer_SN_3</c>. Sourced from the builder, never guessed.
        /// </summary>
        private const string WallNamePrefix = "m_Name: Wall_";
        private const string RuinNamePrefix = "m_Name: Ruin_Wall_";

        [UnityEditor.MenuItem("Tools/Regression/Raid Scene Coverage")]
        public static void RunAll()
        {
            bool ok = Run(out string reason);
            Debug.Log((ok ? "RAID_SCENE_COVERAGE_OK :: " : "RAID_SCENE_COVERAGE_FAIL :: ") + reason);
        }

        /// <summary>DataRegression-shaped contract. Never throws.</summary>
        public static bool Run(out string reason)
        {
            var failures = new List<string>();
            var log = new StringBuilder();
            log.AppendLine("--- RAID SCENE COVERAGE (config -> generated scene) ---");

            try
            {
                var configs = LoadRaidConfigs(failures, log);
                CaseSceneExists(configs, failures, log);
                CaseRegistered(configs, failures, log);
                CaseCurrentPartition(configs, failures, log);
                CaseNavBakeListCovers(configs, failures, log);
                CaseNoOrphanScenes(configs, failures, log);
            }
            catch (Exception ex)
            {
                // The contract is "never throws" - a bug in the oracle is a FAIL, not a crash.
                failures.Add("oracle threw: " + ex.GetType().Name + " " + ex.Message);
            }

            if (failures.Count > 0)
            {
                reason = failures.Count + " failure(s): " + string.Join(" | ", failures.Take(8)) +
                         (failures.Count > 8 ? $" (+{failures.Count - 8} more)" : "");
                Debug.Log(log.ToString());
                return false;
            }

            reason = log.ToString().Replace("\r", "").Replace("\n", " ").Trim();
            if (reason.Length > 900) reason = reason.Substring(0, 900) + " ...";
            return true;
        }

        // =====================================================================
        //  Data load
        // =====================================================================

        private sealed class RaidCfg
        {
            public string Id;
            public string SceneName;
            public string ScenePath;
        }

        /// <summary>
        /// The raid set, DERIVED from the catalog - deliberately not a hand-kept list,
        /// because a hand-kept list is the defect under test.
        ///
        /// <para>Non-raid rows are excluded by the predicate and that is correct:
        /// <c>village2_enemy_outpost</c> names scene <c>Village2</c> (a hand-built scene with
        /// its own Village2RaidController) and <c>player_outpost</c> names
        /// <c>PlayerOutpost</c>. Neither is a generated RaidBase_* level, and this generator
        /// only ever writes those. Do NOT add them.</para>
        /// </summary>
        private static List<RaidCfg> LoadRaidConfigs(List<string> failures, StringBuilder log)
        {
            var list = new List<RaidCfg>();
            SceneConfigCatalog.Invalidate();
            var all = SceneConfigCatalog.All;
            if (all == null)
            {
                failures.Add("[catalog] SceneConfigCatalog.All returned null - the raid set is unknowable.");
                return list;
            }

            foreach (var cfg in all)
            {
                if (cfg == null || string.IsNullOrEmpty(cfg.id) || string.IsNullOrEmpty(cfg.sceneName)) continue;
                if (!cfg.sceneName.StartsWith("RaidBase", StringComparison.OrdinalIgnoreCase)) continue;
                list.Add(new RaidCfg
                {
                    Id = cfg.id,
                    SceneName = cfg.sceneName,
                    ScenePath = $"{ScenesDir}/{cfg.sceneName}.unity",
                });
            }

            // An EMPTY set must never read as "all clear" - that is how a silent no-op bake
            // reports success (CLAUDE.md sec.11B: marker absence is a failure, not an unknown).
            if (list.Count == 0)
                failures.Add("[catalog] NO scene-config names a RaidBase_* scene. Either the catalog " +
                             "failed to load or the raid rows were removed; both make every case below vacuous.");
            else
                log.AppendLine($"[catalog] {list.Count} raid config(s): " +
                               string.Join(", ", list.Select(c => c.Id + " -> " + c.SceneName)));
            return list;
        }

        // =====================================================================
        //  Case 1 [exists] - the config names a scene that is actually on disk.
        // =====================================================================

        private static void CaseSceneExists(List<RaidCfg> configs, List<string> failures, StringBuilder log)
        {
            foreach (var c in configs)
            {
                if (File.Exists(c.ScenePath)) continue;
                failures.Add($"[exists] config '{c.Id}' declares sceneName '{c.SceneName}' but {c.ScenePath} " +
                             "does not exist - the level was never generated, so RaidDeployVM.cs:443 would " +
                             "hand GoRaid a scene that cannot load.");
            }
            log.AppendLine($"[exists] {configs.Count - failures.Count(f => f.StartsWith("[exists]"))}" +
                           $"/{configs.Count} raid scene file(s) present.");
        }

        // =====================================================================
        //  Case 2 [registered] - GoRaid refuses a scene that is not in the player
        //  build settings, so an existing-but-unregistered scene is still a dead end.
        // =====================================================================

        private static void CaseRegistered(List<RaidCfg> configs, List<string> failures, StringBuilder log)
        {
            string asset = TryRead(BuildSettingsAsset);
            if (asset == null)
            {
                failures.Add("[registered] cannot read " + BuildSettingsAsset);
                return;
            }

            // The asset serializes each entry as two lines: "- enabled: <0|1>" then
            // "  path: <scene path>". Pair them by walking in order rather than regexing
            // across the file, so a disabled entry can never be mistaken for an enabled one.
            var enabledPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            bool pendingEnabled = false;
            bool havePending = false;
            foreach (var raw in asset.Replace("\r", "").Split('\n'))
            {
                string line = raw.Trim();
                if (line.StartsWith("- enabled:", StringComparison.Ordinal))
                {
                    pendingEnabled = line.EndsWith("1", StringComparison.Ordinal);
                    havePending = true;
                }
                else if (line.StartsWith("path:", StringComparison.Ordinal) && havePending)
                {
                    if (pendingEnabled) enabledPaths.Add(line.Substring("path:".Length).Trim());
                    havePending = false;
                }
            }

            int ok = 0;
            foreach (var c in configs)
            {
                if (enabledPaths.Contains(c.ScenePath)) { ok++; continue; }
                failures.Add($"[registered] '{c.Id}' scene {c.ScenePath} is not an ENABLED entry in " +
                             $"{BuildSettingsAsset} - SceneRouter.GoRaid gates on IsSceneRegistered, so the " +
                             "raid would refuse to load in a player build.");
            }
            log.AppendLine($"[registered] {ok}/{configs.Count} raid scene(s) enabled in build settings.");
        }

        // =====================================================================
        //  Case 3 [partition] - THE CASE THAT CATCHES WO-1732.
        //
        //  WO-1723 Lane B made the wall ring one clad panel per WallSegment and bakes a
        //  Ruin_<segName> holder for each so a collapsed wall LOOKS collapsed. A scene
        //  generated before that partition has walls and no ruins - it is walkable once
        //  destroyed (the nav bake covers it) but shows nothing, which is the exact
        //  defect the owner felt. Counting both families off the serialized scene proves
        //  which builder produced the file, with no scene load and no Unity bake.
        // =====================================================================

        private static void CaseCurrentPartition(List<RaidCfg> configs, List<string> failures, StringBuilder log)
        {
            foreach (var c in configs)
            {
                if (!File.Exists(c.ScenePath)) continue;   // already reported by Case 1

                int walls = 0, ruins = 0;
                try
                {
                    foreach (var raw in File.ReadLines(c.ScenePath))
                    {
                        string line = raw.TrimStart();
                        // Order matters: a ruin line also begins "m_Name: Ruin_Wall_", which does
                        // NOT match the wall prefix "m_Name: Wall_", so the two never double-count.
                        if (line.StartsWith(RuinNamePrefix, StringComparison.Ordinal)) ruins++;
                        else if (line.StartsWith(WallNamePrefix, StringComparison.Ordinal)) walls++;
                    }
                }
                catch (Exception ex)
                {
                    failures.Add($"[partition] cannot read {c.ScenePath}: {ex.GetType().Name} {ex.Message}");
                    continue;
                }

                if (walls == 0)
                {
                    failures.Add($"[partition] '{c.Id}' ({c.SceneName}.unity) carries NO Wall_* segments at all - " +
                                 "it is not a generated raid ring.");
                    continue;
                }

                if (ruins != walls)
                {
                    failures.Add($"[partition] '{c.Id}' ({c.SceneName}.unity) has {walls} Wall_* segment(s) but " +
                                 $"{ruins} Ruin_Wall_* rubble holder(s). Since WO-1723 Lane B the generator bakes " +
                                 "exactly ONE ruin per segment, so this scene predates the current clad-module " +
                                 "partition: a destroyed wall there becomes walkable WITHOUT ever looking " +
                                 "destroyed. Re-run DeNelle.Editor.RaidBaseGenerator.BuildAllRaidScenes then " +
                                 "DeNelle.Editor.RaidNavBake.BakeAll.");
                    continue;
                }

                log.AppendLine($"[partition] {c.Id}: {walls} wall(s), {ruins} ruin(s) - 1:1.");
            }
        }

        // =====================================================================
        //  Case 4 [bake-list] - RaidNavBake keeps its own scene-path list. A raid scene
        //  the generator writes but the bake list omits has no navmesh; one the bake list
        //  names but the catalog does not is a stale path. Read as SOURCE TEXT because
        //  DeNelle.EditorRegression does not reference DeNelle.Editor - the same
        //  source-scan convention RaidArenaShapeRegression already uses.
        // =====================================================================

        private static void CaseNavBakeListCovers(List<RaidCfg> configs, List<string> failures, StringBuilder log)
        {
            string src = TryRead(NavBakeSrc);
            if (src == null)
            {
                failures.Add("[bake-list] cannot read " + NavBakeSrc);
                return;
            }

            int missing = 0;
            foreach (var c in configs)
            {
                if (src.IndexOf(c.ScenePath, StringComparison.Ordinal) >= 0) continue;
                missing++;
                failures.Add($"[bake-list] {NavBakeSrc} does not name {c.ScenePath}, so raid '{c.Id}' would be " +
                             "generated and then never nav-baked - nothing in it can walk.");
            }

            // And the other direction: a path the bake list still names that no config claims.
            foreach (var raw in src.Replace("\r", "").Split('\n'))
            {
                string line = raw.Trim();
                int q = line.IndexOf($"\"{ScenesDir}/RaidBase", StringComparison.Ordinal);
                if (q < 0) continue;
                int start = q + 1;
                int end = line.IndexOf('"', start);
                if (end <= start) continue;
                string path = line.Substring(start, end - start);
                if (configs.Any(c => string.Equals(c.ScenePath, path, StringComparison.OrdinalIgnoreCase))) continue;
                failures.Add($"[bake-list] {NavBakeSrc} names {path}, which no scene-config claims - a stale " +
                             "path in the bake list, or a raid row that was removed from scene-configs.json.");
            }

            log.AppendLine($"[bake-list] {configs.Count - missing}/{configs.Count} raid scene(s) named by RaidNavBake.");
        }

        // =====================================================================
        //  Case 5 [orphan] - a RaidBase_*.unity on disk that NO config claims.
        //
        //  This is the trap WO-1732 was one edit away from springing: had the fix simply
        //  added "iron_bastion" to the old array while BuildSceneFor still composed
        //  RaidBase_{id}, the bake would have written a NEW RaidBase_iron_bastion.unity
        //  and left the live RaidBase_IronBastion.unity stale - two scenes, the wrong one
        //  loaded, and every other case above still green. An unclaimed raid scene is
        //  either that mistake or a rename that never finished; both are failures.
        // =====================================================================

        private static void CaseNoOrphanScenes(List<RaidCfg> configs, List<string> failures, StringBuilder log)
        {
            string[] onDisk;
            try { onDisk = Directory.GetFiles(ScenesDir, "RaidBase_*.unity", SearchOption.TopDirectoryOnly); }
            catch (Exception ex)
            {
                failures.Add($"[orphan] cannot list {ScenesDir}: {ex.GetType().Name} {ex.Message}");
                return;
            }

            int orphans = 0;
            foreach (var raw in onDisk)
            {
                string path = raw.Replace('\\', '/');
                if (configs.Any(c => string.Equals(c.ScenePath, path, StringComparison.OrdinalIgnoreCase))) continue;
                orphans++;
                failures.Add($"[orphan] {path} exists but no scene-config claims it. Either a generator wrote a " +
                             "scene path composed from the config ID instead of its authored sceneName (the " +
                             "WO-1732 trap - the live scene then silently goes stale), or a raid row was removed " +
                             "from scene-configs.json and its scene was left behind.");
            }
            log.AppendLine($"[orphan] {onDisk.Length} RaidBase_*.unity on disk, {orphans} unclaimed.");
        }

        // =====================================================================
        //  Helpers
        // =====================================================================

        private static string TryRead(string path)
        {
            try { return File.Exists(path) ? File.ReadAllText(path) : null; }
            catch { return null; }
        }
    }
}
