// =============================================================================
// HeroAnimatorFactory — builds per-class hero AnimatorControllers from the
// Mixamo clips in Assets/Action/ (WO-140). Replaces the obsolete Tripo-era
// HeroAnimatorSetup (which scraped 2 generic NLA takes per FBX).
// -----------------------------------------------------------------------------
// Data-driven: ONE Build(HeroSpec) algorithm consumes a per-class spec, so the
// three heroes are three spec literals (not three code paths) — refactor-ready
// toward a shared AnimatorBuildSpec when the catalog grows (NOT a meta-factory;
// see WO-140). NOT recursive: a controller is a flat state list + a blend tree.
//
// Runtime contract (verified in HeroLocomotion/HeroAbilities, 2026-05-30):
//   Speed   (float)   — HeroLocomotion sets = velocity magnitude → Idle/Walk/Run
//   Cast    (trigger) — HeroAbilities.TryCast → the class attack
//   Victory (trigger) — HeroLocomotion on wave clear → victory pose
// Controllers load via Resources.Load("Heroes/<slug>") where slug ∈
// {Knight, Ranger, Mage}; output paths are fixed at Resources/Heroes/<slug>.controller.
//
// Clips are Humanoid (Assets/Action are animationType 3 + CreateFromThisModel),
// so one clip retargets onto every hero. Every clip lookup is null-guarded — a
// missing FBX logs a warning and skips that state; the build still completes.
// =============================================================================
using System.Collections.Generic;
using System.IO;
using DeNelle.Core.Combat;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace DeNelle.Editor
{
    public static class HeroAnimatorFactory
    {
        // WO-283: clips now live in per-type subfolders under Assets/Action/. Each
        // hero searches its type folder first, then Shared/ (the base set every model
        // retargets). ActionDir kept for the legacy flat-folder fallback.
        private const string ActionDir = "Assets/Action/";
        private const string SharedDir = "Assets/Action/Shared/";

        // ── WO-217 / WO-218 tuning ───────────────────────────────────────────
        // Attack/cast snappiness (WO-217): play the swing faster + recover quick.
        // Lowered exit times for "attack fast with animation cycles" on rapid button
        // presses (especially important for Ranger archer aim/fire cycles while the
        // OTS camera is surveying and targeting). The clip plays the cycle, then
        // quickly returns to ready/locomotion so the next press feels immediate.
        private const float AttackSpeed  = 1f;     // authored 1.0x (owner "go with defaults" 2026-07-03; was 1.3f WO-217 snappy-swing — mocap plays at natural speed)
        private const float CastExitTime = 0.38f;  // quick return for fast re-trigger / cycle chaining
        private const float CastExitDur  = 0.03f;  // very tight blend back to ready pose
        // Upper-body attack layer (WO-218): lets the hero swing/cast while moving.
        // Mask generated by EnsureUpperBodyMask(); arms+torso enabled, legs+root off.
        private const string UpperMaskPath = "Assets/Generated/Animators/HeroUpperBody.mask";
        // WO-218: Speed threshold (raw world u/s) below which the hero is "standing".
        // The BASE-layer Cast/Attack (full-body swing) only fires when standing; while
        // MOVING the base layer STAYS in Locomotion (legs keep walking/running) and the
        // upper-body layer alone carries the swing — so the attack no longer freezes the
        // legs. Tuned below the walk centre (6) so any real locomotion gates the full
        // -body version. Idle/near-idle (< this) still plays the clean full-body attack.
        private const float StandingSpeedMax = 2.0f;

        // ── DEATH IS TERMINAL ON THE BASE LAYER (F8 seq 4647, 2026-09-02) ────────────
        // The 2026-08-30 fix made the DEATH transitions mutually exclusive with each other
        // (the generic fallback carries DeathDir != N for every directional state actually
        // built — see the Death block in Build). That landed and is live in every built
        // controller. It was NOT sufficient, and the captured line proves it: the re-entry
        // detector still fired 3 base-layer state changes in 0.25s on ctrl='Mage'.
        //
        // The remaining collision is NOT death-vs-death, it is death-vs-ACTION. Every other
        // AnyState transition on the base layer (Cast, Cast_q/w/e/r, Attack{N}, Hit, Victory)
        // carried NO Dead guard, and each is standing-gated on Speed < StandingSpeedMax —
        // which a dead, pinned hero satisfies permanently (Speed == 0). So a Hit trigger from
        // the killing blow, an overkill hit, a lingering AoE tick, or a wave-clear Victory
        // fires WHILE Dead is latched:
        //   Death -> (Any->Hit matches) -> Hit -> AddActionReturn exits at 0.28 -> Locomotion
        //         -> (Any->Death matches again, Dead still latched) -> Death restarts frame 0
        // three base-layer changes inside a quarter second, the death clip never advances past
        // its opening frames, and the body reads as a SHAKE — the exact signature the detector
        // describes.
        //
        // FIX: once Dead latches, NOTHING but a death state may be entered. Every non-death
        // AnyState transition (base layer AND the upper-body overlay, which shares the same
        // Cast/Attack triggers and would otherwise swing a corpse's arms) now carries
        // Dead == false. Combined with the death-vs-death guards this makes the base layer's
        // AnyState set totally mutually exclusive for every (Dead, DeathDir) combination.
        // Do NOT remove this guard to "let the death flinch play" — the flinch IS the shake.
        private static void AddNotDead(AnimatorStateTransition t) =>
            t.AddCondition(AnimatorConditionMode.IfNot, 0f, "Dead");

        // Shared locomotion clips (all classes) — canonical WO-283 Shared/ basenames.
        private const string IdleClip      = "Shared_Idle";
        private const string WalkClip      = "Shared_Walk_Forward";
        private const string RunClip       = "Shared_Run_Forward";
        private const string VictoryClip   = "Shared_Victory_Pose";

        // WO-284/285 shared combat clips — every hero retargets these from Shared/.
        private const string HitClip       = "Shared_Hit_Reaction";
        private const string DeathClip     = "Shared_Death";
        private const string BlockClip     = "Shared_Block";

        // RANGER BOW FIRE (owner defect 2026-08-16). The one real bow-loose clip in the project.
        // Lives in the FLAT Assets/Action/ folder, which LoadClip always appends as its last
        // search root, so the Ranger spec resolves it without adding a root. Named as a const
        // because RangerBowFireRegression lints for it by name -- a raw literal buried in a spec
        // is exactly how the aim-idle binding survived unnoticed for months.
        public const string RangerBowFireClip = "Archery Shot Away";

        // WO-493 #5 / WO-497: HERO injured-stance locomotion. Reuses the same retargetable
        // Humanoid injured clips the ENEMY half uses (Assets/Action/Enemies/injured*.fbx) —
        // a wounded idle/limp/stagger sub-tree entered when the Injured bool is set (the
        // hero drops below ~30% HP; HeroHealth drives ActorAnimator.SetInjured). Mirrors
        // BuildOrcHumanoidController's InjuredLocomotion swap. Null-guarded: a missing clip
        // falls back to the healthy locomotion so the state is never empty.
        private static readonly string[] InjuredRoots = { "Assets/Action/Enemies/" };
        // Injured IDLE upgraded 2026-07-03: "injured hurting idle" (hurt-but-standing, clutching
        // the wound, rooted) replaces the flat "injured idle" placeholder — cleaner wounded read.
        // Same Humanoid mixamo rig (animationType:3) so it retargets onto the hero avatar exactly
        // like the old clip; null-guarded fallback to healthy idle is unchanged.
        private const string InjuredIdleClip = "injured hurting idle";
        private const string InjuredWalkClip = "injured walk";
        private const string InjuredRunClip  = "injured run";

        // Directional death clips (DeathDir int: 0=Fall/centre, 1=Left, 2=Right). When
        // present, a "Death1"/"Death2" state is gated on Dead==true AND DeathDir==N so a
        // hit from the side topples the right way; the plain Death covers DeathDir 0.
        private const string DeathLeftClip  = "Shared_Standing_Death_Left";
        private const string DeathRightClip = "Shared_Standing_Death_Right";

        private struct HeroSpec
        {
            public string slug;            // Knight | Ranger | Mage | Cleric
            public string controllerPath;  // Resources/Heroes/<slug>.controller
            public string castClip;        // per-class spell/cast clip basename (the generic / variant-0 cast)
            public string castClipFallback;// used + warned if the primary is absent
            public string[] attackClips;   // WO-285: melee combo (Knight = 3, else 1)
            public string[] searchRoots;   // WO-283: type folder first, then Shared/

            // PER-SPELL CASTS: one clip per ability slot, indexed by CastVariant 1..4
            // (q/w/e/r). HeroAbilities.TryCast(slot) fires Cast with CastVariant = slot+1,
            // so the matching CastN state plays that spell's own animation. Index 0 is
            // unused/ignored (variant 0 = the generic `castClip` state). A null/missing
            // entry is skipped (that slot falls back to the generic Cast). Length may be
            // < 5; only the present indices build states.
            public string[] spellCastClips;

            // MOCAP-LOCOMOTION VARIANT (owner 2026-07-04): optional per-spec overrides for the
            // Locomotion blend-tree clip basenames. When null (every stock hero) the shared
            // Idle/Walk/Run constants are used unchanged. BuildKnightMocapController sets these to the
            // studio-mocap sword+shield clips so KnightMocap.controller swaps ONLY its locomotion
            // sources — Cast/Attack/Hit/Death/Block/Victory/UpperBody/Injured stay byte-identical to
            // the stock Knight build.
            public string idleClipOverride;
            public string walkClipOverride;
            public string runClipOverride;

            // COMBAT-STANCE SPLIT + MOCAP COMBAT (owner 2026-07-04, KnightMocap V1). All optional;
            // null/0 on every stock hero → the shared single-tree, Mixamo-combat build is produced
            // BYTE-IDENTICAL. Set only by BuildKnightMocapController.
            //   combatIdleClipOverride — when non-null, builds a SECOND locomotion tree
            //     ("CombatLocomotion") whose idle is this braced/ready pose (mocap: idle_ready) while
            //     the DEFAULT Locomotion idle stays the CALM idleClipOverride (mocap: m-standby-idle).
            //     Locomotion ⇄ CombatLocomotion flips on the InCombat bool (ActorAnimator.SetCombatStance).
            //     RCA fix: the hero no longer stands sword-ready in town — calm out of combat, braced in.
            //   blockClipOverride / hitClipOverride — swap Block/Hit onto the SAME CC_Base AccuRig
            //     (shield_block* / m-ss-damage*) instead of the lossy cross-rig Mixamo Shared clips,
            //     so the FIGHT shows the purpose-built sword+shield motion.
            //   combatActionExitTime — >0 lets MORE of the attack/cast swing play before returning
            //     (readability: wind-up→impact→recovery reads) vs the snappy 0.38 stock cut.
            public string combatIdleClipOverride;
            // Optional combat-only gait — when set, CombatLocomotion uses these instead of the calm
            // walk/run clips (KnightMocap: Shared walk in town, sword+shield gait in a fight).
            public string combatWalkClipOverride;
            public string combatRunClipOverride;
            public string blockClipOverride;
            public string hitClipOverride;
            public float  combatActionExitTime;

            // TURN-IN-PLACE TIER (owner 2026-07-04, KnightMocap full-turning). All optional; null on
            // every stock hero → no TurnDir param and no turn states are built, so those controllers stay
            // BYTE-IDENTICAL. When supplied, Build() declares the TurnDir int and BuildTurnInPlace wires
            // one in-place turn state per clip, entered from the (calm/combat) locomotion tree when the
            // hero is ~stationary (Speed < StandingSpeedMax) and HeroLocomotion has set TurnDir to that
            // value (−1 Left90 / 1 Right90 / −2 Left180 / 2 Right180). Cosmetic: HeroLocomotion still owns
            // the actual yaw (LookRotation slerp) — these clips just show the pivot instead of a foot-slide.
            public string turnLeftClip;      // TurnDir −1 (90° left)
            public string turnRightClip;     // TurnDir  1 (90° right)
            public string turnLeft180Clip;   // TurnDir −2 (180° left / about-face)
            public string turnRight180Clip;  // TurnDir  2 (180° right / about-face)

            // PREBATTLE unsheathe (KnightMocap): draw-weapon clip basename played standing
            // when InCombat flips true before entering CombatLocomotion. Null = direct flip.
            public string unsheatheClipOverride;

            // ACTION KEYWORD REGISTRY seam (F8 2026-07-11 "all four ability animations are
            // the same"): when non-null, the cast path resolves through the Motion Caster
            // registry with the hardcoded pick as terminal default — generic cast = `cast`,
            // Cast_q = `skill1`, Cast_w = `skill2`, Cast_e = `castHeal` (r stays hardcoded) —
            // mirroring KnightPackageControllerBuilder EXACTLY (:316-328) so the owner's picks
            // apply to whichever controller is live. Null (every stock hero) = no registry
            // lookup, byte-identical build. Set only by BuildKnightMocapController ("knight").
            public string castingTarget;

            // Extended directional deaths (KnightMocap): .anim asset paths under the package
            // extract folder — Humanoid retarget onto CC_Base. Null = skip that bucket.
            public string deathFrontAnimPath;
            public string deathBackAnimPath;
        }

        private const string PackageExtractDir =
            "Assets/HeroPackages/Knight/Animations/Extracted/";

        // WO-283 §1 type->folder mapping. Casters (Mage + Cleric) share the Wizard set.
        private static readonly string[] KnightRoots = { "Assets/Action/Knight/",  SharedDir };
        private static readonly string[] RangerRoots = { "Assets/Action/Ranger/",  SharedDir };
        private static readonly string[] WizardRoots = { "Assets/Action/Wizard/",  SharedDir };

        private static readonly HeroSpec[] Specs =
        {
            new HeroSpec { slug = "Knight",
                controllerPath = "Assets/Resources/Heroes/Knight.controller",
                castClip = "standing melee attack horizontal",
                castClipFallback = "standing melee combo attack ver. 1",
                // WO-285: 3-swing melee combo cycled by the Combo int.
                attackClips = new[] { "standing melee attack horizontal",
                                      "standing melee combo attack ver. 1",
                                      "standing melee combo attack ver. 2" },
                // Per-slot "cast"/special swings (q=Shield Bash strike, w=Bulwark Slam
                // cleave, e=Oath Ward buff pose, r=Lantern Charge cleave ult). The Knight
                // mostly routes through the melee Attack at runtime, but firing Cast with a
                // variant gives each ability slot a distinct swing/pose when the cast path runs.
                spellCastClips = new[] {
                    null,                                   // [0] unused (generic = castClip)
                    "standing melee attack horizontal",     // [1] q  Shield Bash
                    "standing melee attack 360 high",       // [2] w  Bulwark Slam (sweeping)
                    "sword and shield power up",            // [3] e  Oath Ward (buff/ward pose)
                    "standing melee attack downward",       // [4] r  Lantern Charge (heavy)
                },
                // Held defensive pose authored for sword + shield: the left arm visibly raises
                // and presents the equipped off-hand shield for the entire Block bool window.
                blockClipOverride = "sword and shield block idle",
                searchRoots = KnightRoots },
            new HeroSpec { slug = "Mage",
                controllerPath = "Assets/Resources/Heroes/Mage.controller",
                castClip = "Wizard_Spell_Cast", castClipFallback = "Standing 1H Magic Attack 01",
                attackClips = new[] { "Wizard_Spell_Cast" },   // caster: basic attack = cast
                // Per-spell casts: q Arcane Bolt (1H snap), w Frost Nova (2H area), e Healing
                // Beacon (heal), r Meteor Strike (2H heavy). Each abilities.json slot now plays
                // its own Wizard cast clip.
                spellCastClips = new[] {
                    null,                                   // [0] unused
                    "Standing 1H Magic Attack 01",          // [1] q  Arcane Bolt
                    "Standing 2H Magic Area Attack 01",     // [2] w  Frost Nova
                    "Wizard_Heal",                          // [3] e  Healing Beacon
                    "Standing 2H Magic Attack 03",          // [4] r  Meteor Strike (ult)
                    "standing 1H cast spell 01",            // [5] Arcane Shell
                    "Standing 1H Magic Attack 02",          // [6] Drain
                    "Standing 2H Magic Attack 04",          // [7] Poison Cloud
                    "Standing 2H Magic Area Attack 01",     // [8] Frost Nova
                    "Standing 2H Cast Spell 01",            // [9] Manaweave
                    "Standing 2H Magic Area Attack 02",     // [10] Void Rift
                    "Wizard_Spell_Cast",                    // [11] Blink
                    "Standing 2H Magic Attack 05",          // [12] Cataclysm
                    "Standing 1H Magic Attack 03",          // [13] Thunder
                    "Wizard_Heal",                          // [14] Mend
                    "Standing 2H Magic Attack 03",          // [15] Meteor Strike
                    "Standing 2H Magic Attack 01",          // [16] Syphon Essence
                    "Standing 2H Magic Attack 02",          // [17] Wither
                },
                searchRoots = WizardRoots },
            // RANGER FIRE CLIP (owner defect 2026-08-16): the ranger had NO firing animation.
            // Attack, Cast and CastUpper all bound Ranger_Aim_Idle -- a STATIC aim pose -- so
            // every shot the owner fired froze the hero mid-aim while the arrow flew. The old
            // comment here called that "cosmetic-only"; it is not, it is the whole read of the
            // attack. Assets/Action/Archery Shot Away.fbx (clip 'archery-shotaway', Humanoid /
            // animationType 3, so it retargets onto the ranger avatar for free) was already
            // imported and bound to NOTHING. It is now the ranger's fire motion.
            //   - castClip     -> the bow shot. HeroAbilities.TryCast fires the Cast trigger and
            //                     the ranger has no spellCastClips, so ALL FOUR ability slots
            //                     fall back to this generic Cast state = every ranger skill now
            //                     looses an arrow instead of holding the aim pose.
            //   - attackClips  -> the same shot, so the basic/melee-verb path (troop archers +
            //                     the Attack trigger) fires the bow too.
            //   - the FALLBACK is the aim idle: if the archery FBX is ever removed we degrade to
            //     the old (bad but non-empty) behaviour rather than building an empty state.
            // Ranger_Aim_Idle is now bound ONLY as the fallback: it is a POSE, and a pose is an
            // idle, never a fire. (It is not currently bound to any built Ranger state -- the
            // ranger has no combat-stance state; giving it one is a separate ticket, not this
            // one.) RangerBowFireRegression pins that the fire states no longer collapse onto
            // it. A future draw/volley/rapid-fire split wants real clips
            // (weaponskill-animations.json ranger rows still carry clipExists:false for those).
            new HeroSpec { slug = "Ranger",
                controllerPath = "Assets/Resources/Heroes/Ranger.controller",
                castClip = RangerBowFireClip, castClipFallback = "Ranger_Aim_Idle",
                attackClips = new[] { RangerBowFireClip },
                searchRoots = RangerRoots },
            // Cleric (caster) shares the Wizard set; Heal is its primary cast.
            new HeroSpec { slug = "Cleric",
                controllerPath = "Assets/Resources/Heroes/Cleric.controller",
                castClip = "Wizard_Heal", castClipFallback = "Wizard_Spell_Cast",
                attackClips = new[] { "Wizard_Heal" },
                // Cleric per-spell casts (caster kit shares the Wizard clips): q smite,
                // w consecrate area, e Heal (its signature), r big channel.
                spellCastClips = new[] {
                    null,                                   // [0] unused
                    "Standing 1H Magic Attack 02",          // [1] q  smite
                    "Standing 2H Magic Area Attack 02",     // [2] w  consecrate (area)
                    "Wizard_Heal",                          // [3] e  Heal (signature)
                    "Standing 2H Cast Spell 01",            // [4] r  channel ult
                },
                searchRoots = WizardRoots },
        };

        [MenuItem("Defenders/Animation/Build Hero Animators (Mixamo)")]
        public static void BuildAll()
        {
            foreach (var spec in Specs) Build(spec);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("[HeroAnimatorFactory] BuildAll complete — Knight / Mage / Ranger / Cleric.");
        }

        // MOCAP LOCOMOTION (owner 2026-07-04, ff.mocaploco): the professional studio-mocap sword+shield
        // locomotion clips (HUMANOID, on the SAME CC_Base rig as KnightV3 → ~1:1 retarget). Each FBX ships
        // a "0_T-Pose" take alongside the motion take; LoadClip already skips the T-pose by name.
        private const string MocapMovesDir = "Assets/Action/Knight/Motion/studio-mocap-sword-and-shield-moves/";
        // The magical-moves pack sits on the SAME CC_Base rig; it carries the calm standby idle and
        // the sword+shield stagger/damage reactions the sword+shield-moves pack lacks.
        private const string MocapMagicalDir = "Assets/Action/Knight/Motion/studio-mocap-series-magical-moves/";
        // CALM default idle (relaxed standby) vs the BRACED in-combat idle (sword+shield ready) — the
        // combat-stance split. Walk/run are the sword+shield gait for both trees (no calm-gait clip
        // exists in-pack; the braced walk/run read fine relaxed and are 1:1 on the rig).
        private const string MocapIdleClip       = "m-standby-idle";   // calm (magical-moves)
        private const string MocapCombatIdleClip = "idle_ready";       // braced/ready (sword+shield)
        private const string MocapWalkClip = "walkforward01";
        private const string MocapRunClip  = "runforward_218667";
        // TURN-IN-PLACE (owner 2026-07-04): the studio-mocap sword+shield in-place pivots. Same AccuRig
        // (animationType:3, verified) as the gait, one motion take each ("turnleft90"/etc, the "0_T-Pose"
        // take is skipped by LoadClip). 90s are the everyday quarter-turn; 180s cover the about-face.
        private const string MocapTurnLeftClip     = "turnleft90";
        private const string MocapTurnRightClip    = "turnright90";
        private const string MocapTurnLeft180Clip  = "turnleft180";
        private const string MocapTurnRight180Clip = "turnright180";
        // MOCAP COMBAT (owner 2026-07-04): the purpose-built AccuRig sword+shield swings/block/stagger.
        // A 3-swing combo that ESCALATES for readability (right slash → left slash → spin finisher);
        // block = raise shield (clear telegraph); hit = sword+shield stagger. All verified Humanoid
        // (animationType:3) + path-confirmed before referencing.
        private static readonly string[] MocapAttackClips = { "atk_slashright", "atk_slashleft", "atk_spin" };
        private static readonly string[] MocapSpellClips  = { null, "atk_stab", "atk_slashleft", "atk_slashright", "atk_slashup" }; // R (variant 4) = "Jump into Slash Up" (WO-750; was atk_spin, de-dup from W)
        private const string MocapCastClip  = "atk_slashright"; // generic cast + upper-body (moving) swing
        private const string MocapBlockClip = "shield_blockup";
        private const string MocapHitClip   = "m-ss-damage-01"; // magical-moves stagger (same rig)
        // Let more of the AccuRig swing play (wind-up → impact → recovery reads) before returning,
        // vs the stock 0.38 snappy cut — the fight must SHOW the motion.
        private const float  MocapActionExitTime = 0.85f;
        // The mocap-locomotion twin controller — bound by HeroBodySwapper for the KnightV3 body when
        // ff.mocaploco is ON. NEVER overwrites Knight.controller.
        private const string KnightMocapControllerPath = "Assets/Resources/Heroes/KnightMocap.controller";

        /// <summary>
        /// OWNER 2026-07-04: builds <c>Resources/Heroes/KnightMocap.controller</c> — a twin of the Knight
        /// controller whose ONLY difference is that its Locomotion (Idle/Walk/Run) sources are the studio
        /// -mocap sword+shield clips instead of the lossy cross-rig Mixamo Shared clips. Reuses the exact
        /// same <see cref="Build"/> path (a cloned Knight <see cref="HeroSpec"/> + the mocap locomotion
        /// overrides + the mocap folder prepended to the search roots), so Cast/Attack/Hit/Death/Block/
        /// Victory/UpperBody/Injured are produced byte-for-byte identical to the Knight build. Does NOT
        /// touch Knight.controller (separate output path). Batchmode-callable:
        /// <c>DeNelle.Editor.HeroAnimatorFactory.BuildKnightMocapController</c>.
        /// </summary>
        [MenuItem("Defenders/Animation/Build Knight Mocap Locomotion Controller")]
        public static void BuildKnightMocapController()
        {
            HeroSpec knight = default;
            bool found = false;
            foreach (var s in Specs) if (s.slug == "Knight") { knight = s; found = true; break; }
            if (!found)
            {
                Debug.LogError("[HeroAnimatorFactory] Knight spec not found — cannot build KnightMocap.controller.");
                return;
            }

            var mocap = knight;   // struct copy — inherits Knight's cast/attack/spell clip sets verbatim
            mocap.slug           = "KnightMocap";                 // logging only (slug is not used for lookups in Build)
            mocap.controllerPath = KnightMocapControllerPath;     // NEVER Knight.controller
            // LoadClip is NON-RECURSIVE — the mocap folder MUST be listed EXPLICITLY, and FIRST so the
            // locomotion basenames resolve there. Knight/Shared still follow, covering cast/attack/hit/
            // death/block/victory exactly as the stock Knight build.
            // LoadClip is NON-RECURSIVE — list BOTH mocap folders FIRST (moves = idle_ready/walk/run/atk_*;
            // magical = m-standby-idle + m-ss-damage stagger), then Knight/Shared cover anything unmapped.
            var roots = new List<string> { MocapMovesDir, MocapMagicalDir };
            roots.AddRange(knight.searchRoots);
            mocap.searchRoots = roots.ToArray();
            // Locomotion: CALM default idle + BRACED combat idle (the stance split), sword+shield gait.
            mocap.idleClipOverride       = MocapIdleClip;        // m-standby-idle (calm, default Locomotion)
            mocap.combatIdleClipOverride = MocapCombatIdleClip;  // idle_ready (braced, InCombat)
            mocap.walkClipOverride       = WalkClip;             // Shared_Walk_Forward — upright town gait
            mocap.runClipOverride        = RunClip;              // Shared_Run_Forward (rarely reached; town speed-capped)
            // FIX 2 (owner "combat walk, he sits in combat idle bent over"): the in-place AccuRig combat
            // gait (walkforward01/runforward) is retargeting-warned + applyRootMotion=false, so the stride
            // reads as a braced weight-shift barely distinct from the combat idle. Reuse the SHARED calm
            // walk/run — which read as a proper stride on the live avatar — for the combat tree too, so
            // combat walk/run = the same good-looking gait, just entered in the combat (braced-idle) stance.
            // Tree structure / thresholds / Speed param are UNCHANGED (they're correct).
            mocap.combatWalkClipOverride = WalkClip;             // Shared_Walk_Forward (was MocapWalkClip)
            mocap.combatRunClipOverride  = RunClip;              // Shared_Run_Forward  (was MocapRunClip)
            // Combat onto the AccuRig sword+shield set (the FIGHT shows the purpose-built motion), with
            // readable swing timing. Melee combo + generic/per-spell casts + block + hit all swap; every
            // other state stays as the Knight build.
            mocap.attackClips          = MocapAttackClips;
            mocap.spellCastClips       = MocapSpellClips;
            mocap.castClip             = MocapCastClip;
            mocap.castClipFallback     = null;
            mocap.blockClipOverride    = MocapBlockClip;
            mocap.hitClipOverride      = MocapHitClip;
            mocap.combatActionExitTime = MocapActionExitTime;
            // TURN-IN-PLACE tier: full directional turning (90 + about-face 180). Only KnightMocap sets
            // these, so only KnightMocap.controller gains the TurnDir param + turn states.
            mocap.turnLeftClip     = MocapTurnLeftClip;
            mocap.turnRightClip    = MocapTurnRightClip;
            mocap.turnLeft180Clip  = MocapTurnLeft180Clip;
            mocap.turnRight180Clip = MocapTurnRight180Clip;
            // ACTION KEYWORD REGISTRY seam (F8 2026-07-11 "all four ability animations are the
            // same"): resolve the cast path through the Motion Caster registry — cast/skill1/
            // skill2/castHeal — so the owner's picks (Heroic Leap = SwordShield_Jump, W = plain
            // Slash, heal = MagicalMoves_SpellCast_02) apply to THIS live controller exactly as
            // they do to the package controller. Registry miss = the MocapSpellClips pick verbatim.
            mocap.castingTarget = "knight";
            // Prebattle draw (Mixamo Humanoid on CC_Base) + package directional deaths.
            mocap.unsheatheClipOverride = "draw sword 1";
            mocap.deathFrontAnimPath = PackageExtractDir + "Signature_Death_Forward.anim";
            mocap.deathBackAnimPath  = PackageExtractDir + "Signature_Standing_Death_Backward_01.anim";

            Build(mocap);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            string atkCombo = string.Join("/", MocapAttackClips);
            Debug.Log($"[HeroAnimatorFactory] KnightMocap.controller built — calm idle ({MocapIdleClip}) + braced " +
                      $"combat idle ({MocapCombatIdleClip}) split on InCombat; calm gait ({WalkClip}/{RunClip}) + " +
                      $"combat gait ({WalkClip}/{RunClip}); " +
                      $"AccuRig combat (atk combo {atkCombo}, block {MocapBlockClip}, hit {MocapHitClip}); " +
                      $"turn-in-place (90 {MocapTurnLeftClip}/{MocapTurnRightClip} + 180 {MocapTurnLeft180Clip}/{MocapTurnRight180Clip}) on TurnDir; " +
                      "cast path registry-resolved (knight.cast/skill1/skill2/castHeal → Cast/Cast_q/w/e states, " +
                      "owner picks; misses = hardcoded mocap picks) " +
                      $"→ {KnightMocapControllerPath}. Bound for KnightV3 when ff.mocaploco=1.");
        }

        private static void Build(HeroSpec spec)
        {
            // Locomotion sources honor the optional per-spec overrides (mocap variant); null → shared constants.
            AnimationClip idle    = LoadClip(spec.idleClipOverride ?? IdleClip, spec.searchRoots);
            // F8 2026-07-11 "walk dragging left foot": the Shared_Walk/Run_Forward Mixamo
            // takes carry a BAKED left hip list (HeroDrift proof: hipsLocalX −0.25/+0.02 on a
            // zero-turn single-clip stride) — the movement code is innocent. Route the calm
            // walk/run through the Motion Caster registry so the clip is re-pickable data
            // (knight.walk / knight.run manual rows); registry miss = today's clip verbatim.
            AnimationClip walk    = MotionCastings.Resolve("knight", "walk",
                                        LoadClip(spec.walkClipOverride ?? WalkClip, spec.searchRoots));
            AnimationClip run     = MotionCastings.Resolve("knight", "run",
                                        LoadClip(spec.runClipOverride  ?? RunClip,  spec.searchRoots));
            AnimationClip victory = LoadClip(VictoryClip, spec.searchRoots);
            AnimationClip hit     = LoadClip(spec.hitClipOverride   ?? HitClip,   spec.searchRoots);
            AnimationClip death   = LoadClip(DeathClip, spec.searchRoots);
            AnimationClip deathL  = LoadClip(DeathLeftClip,  spec.searchRoots);
            AnimationClip deathR  = LoadClip(DeathRightClip, spec.searchRoots);
            AnimationClip block   = LoadClip(spec.blockClipOverride ?? BlockClip, spec.searchRoots);
            AnimationClip cast    = LoadClip(spec.castClip, spec.searchRoots);
            if (cast == null && !string.IsNullOrEmpty(spec.castClipFallback))
            {
                cast = LoadClip(spec.castClipFallback, spec.searchRoots);
                if (cast != null)
                    Debug.LogWarning($"[HeroAnimatorFactory] {spec.slug}: cast clip '{spec.castClip}' " +
                                     $"missing — using fallback '{spec.castClipFallback}' (placeholder).");
            }
            // Registry seam (spec.castingTarget, F8 2026-07-11): the generic (variant-0)
            // cast resolves the `cast` keyword with the hardcoded pick as terminal default —
            // mirrors KnightPackageControllerBuilder :316. Registry miss = today's clip verbatim.
            if (!string.IsNullOrEmpty(spec.castingTarget))
                cast = MotionCastings.Resolve(spec.castingTarget, ActionKeywords.Cast, cast);
            // Per-slot cast clips resolved ONCE (loads + per-keyword registry wraps) and
            // reused by BOTH the base-layer Cast_q/w/e/r states and the upper-body overlay,
            // so the two layers stay in lock-step (package builder pattern, :315-317).
            AnimationClip[] spellClips = ResolveSpellCastClips(spec);

            // Idempotent: recreate the controller from scratch.
            AssetDatabase.DeleteAsset(spec.controllerPath);
            var ctrl = AnimatorController.CreateAnimatorControllerAtPath(spec.controllerPath);

            // Canonical AnimParams set (WO-284) — declared on every hero controller so
            // ActorAnimator's guarded verbs all resolve. States exist for the ones with
            // clips; the rest are declared-but-unused (a safe no-op) for future polish.
            ctrl.AddParameter("Speed",    AnimatorControllerParameterType.Float);
            ctrl.AddParameter("InCombat", AnimatorControllerParameterType.Bool);
            ctrl.AddParameter("Attack",   AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("Combo",    AnimatorControllerParameterType.Int);
            ctrl.AddParameter("Cast",     AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("CastVariant", AnimatorControllerParameterType.Int); // which spell (0=generic, q/w/e/r=1..4)
            ctrl.AddParameter("WindUp",   AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("Block",    AnimatorControllerParameterType.Bool);
            ctrl.AddParameter("Hit",      AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("HitDir",   AnimatorControllerParameterType.Int);
            ctrl.AddParameter("Dead",     AnimatorControllerParameterType.Bool);
            ctrl.AddParameter("DeathDir", AnimatorControllerParameterType.Int);
            ctrl.AddParameter("Victory",  AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("Injured",  AnimatorControllerParameterType.Bool); // WO-493 #5 / WO-497: wounded-stance swap
            // TurnDir declared ONLY when this spec builds turn-in-place states (KnightMocap) — keeps every
            // stock hero controller byte-identical. Int selector: 0 None / ±1 90° / ±2 180° (AnimParams.TurnDirection).
            if (HasTurnClips(spec))
                ctrl.AddParameter("TurnDir", AnimatorControllerParameterType.Int);

            var sm = ctrl.layers[0].stateMachine;

            // ── Locomotion: a 1-D blend tree on Speed (Idle→Walk→Run) ──────────
            // HeroLocomotion feeds a scalar Speed, so a 1-D forward blend is the
            // right model (strafe clips left for a later 2-D pass).
            var locoState = sm.AddState("Locomotion");
            sm.defaultState = locoState;

            var blend = new BlendTree { name = "Locomotion", blendType = BlendTreeType.Simple1D,
                                        blendParameter = "Speed",
                                        // CRITICAL: Unity defaults useAutomaticThresholds = true, which
                                        // OVERWRITES the AddChild thresholds with auto-spaced 0/0.5/1 —
                                        // that's why walk@6/run@9 never stuck and the hero skipped walk
                                        // (Speed 0..6 vs thresholds 0/0.5/1 = always max = run). Turn it
                                        // OFF so the explicit thresholds below are honored.
                                        useAutomaticThresholds = false };
            AssetDatabase.AddObjectToAsset(blend, ctrl);
            locoState.motion = blend;
            // Null-guarded children: only add the clips that loaded. Always have at
            // least one motion so the state isn't empty.
            // WALK-FEEL FIX (owner ticket 2026-07-02 "animations didn't feel like walking"):
            // HeroLocomotion feeds Speed = Velocity.magnitude with _moveSpeed = 6, so full
            // stick = 6 m/s — a RUN pace. The old tree centred WALK at 6 (Run at an
            // unreachable 9), so the hero always glided at 6 m/s on a walk-cadence clip;
            // on top of that HeroBodySwapper.HeroAnimSpeed halves ALL animator playback
            // (0.5×), halving the stride cadence again → heavy foot-slide. New bands:
            // idle@0 / walk@2 / run@6 — full speed plays the RUN clip. Per-child timeScale
            // compensates the 0.5× global so LOCOMOTION cadence roughly matches distance
            // travelled without touching the tuned cast/attack playback: walk ×2 (net 1.0×,
            // ~Mixamo walk cadence at ~2 m/s) and run ×3 (net 1.5×, ~4.5 m/s visual stride
            // at 6 m/s travel — close enough to read as running, tune here if needed).
            var added = new List<float>();
            if (idle != null) { blend.AddChild(idle, 0f);  added.Add(0f); }
            if (walk != null) { blend.AddChild(walk, 2f);  added.Add(2f); }
            if (run  != null) { blend.AddChild(run,  6f);  added.Add(6f); }
            ApplyLocomotionCadence(blend);
            if (added.Count == 0)
                Debug.LogWarning($"[HeroAnimatorFactory] {spec.slug}: no locomotion clips found — " +
                                 "Locomotion state is empty.");

            // ── COMBAT-STANCE SPLIT (KnightMocap V1) ───────────────────────────
            // When the spec supplies a braced combat idle, build a SECOND locomotion tree
            // (CombatLocomotion) and flip Locomotion ⇄ CombatLocomotion on the InCombat bool
            // (ActorAnimator.SetCombatStance, driven by HeroLocomotion). The default Locomotion
            // keeps the CALM idle, so the hero is relaxed in town and braced in a fight. Stock
            // heroes (combatIdleClipOverride == null) get null here → single-tree build unchanged.
            AnimatorState combatLocoState = BuildCombatLocomotion(ctrl, sm, locoState, walk, run, spec);
            WireCombatStanceTransitions(sm, locoState, combatLocoState, spec);
            // Readability: let more of the AccuRig swing play before returning (mocap), else the
            // stock snappy cut. Shared by Cast / per-spell / Attack returns.
            float actionExit = spec.combatActionExitTime > 0f ? spec.combatActionExitTime : CastExitTime;

            // ── WO-493 #5 / WO-497: Injured locomotion swap ────────────────────
            // A SECOND 1-D blend tree on Speed (the wounded idle/limp/stagger),
            // entered when Injured==true and returned when Injured==false — the hero
            // reads "hurt" below ~30% HP (HeroHealth.UpdateInjuredState drives
            // ActorAnimator.SetInjured). Mirrors BuildOrcHumanoidController's swap.
            // Reuses the retargetable Humanoid injured clips from Action/Enemies/;
            // falls back to the healthy locomotion clips so the state is never empty.
            BuildInjuredLocomotion(ctrl, sm, locoState, idle, walk, run, spec);

            // ── TURN-IN-PLACE (KnightMocap full-turning, owner 2026-07-04) ─────
            // Optional: only when the spec supplies turn clips (KnightMocap). Wires one in-place turn
            // state per clip, entered from the calm/combat locomotion tree when the hero pivots to face
            // a new direction while ~stationary (HeroLocomotion drives TurnDir). Stock heroes (no turn
            // clips) skip this entirely → no TurnDir param, no turn states → byte-identical build.
            int turnStates = BuildTurnInPlace(ctrl, sm, locoState, combatLocoState, spec);

            // ── Cast — Any → Cast on the trigger, returns to Locomotion ────────
            // WO-217: snappier — state.speed bumped + tighter exit so recovery is
            // quick. The base-layer Cast is KEPT (full-body fallback / clean attack
            // when standing); the WO-218 upper-body layer overlays the same clip so
            // the hero can also swing WHILE moving.
            // WO-218: GATE this full-body Cast on Speed < StandingSpeedMax so it only
            // fires when standing. While MOVING, the base layer stays in Locomotion
            // (legs keep running) and the upper-body layer alone carries the swing —
            // attacks no longer freeze movement.
            // The GENERIC (variant-0) Cast state — fired when Cast is triggered without a
            // matching per-spell variant (e.g. the no-arg PlayCast() from BattleController /
            // PlayerAttackController). Its Any→Cast transition is UNCONDITIONED on CastVariant
            // so it always wins as the default; the per-variant states below add their own
            // CastVariant==N gate so a specific spell overrides this when set.
            if (cast != null)
            {
                var castState = sm.AddState("Cast");
                castState.motion = cast;
                castState.speed  = AttackSpeed;   // WO-217: faster swing
                var toCast = sm.AddAnyStateTransition(castState);
                toCast.hasExitTime = false; toCast.duration = 0.05f;
                toCast.AddCondition(AnimatorConditionMode.If, 0f, "Cast");
                if (HasAnySpellClip(spellClips))
                    toCast.AddCondition(AnimatorConditionMode.Equals, 0f, "CastVariant");
                toCast.AddCondition(AnimatorConditionMode.Less, StandingSpeedMax, "Speed"); // WO-218: standing only
                AddNotDead(toCast);   // F8 4647: death is terminal — a corpse never casts
                AddActionReturn(castState, locoState, combatLocoState, actionExit, CastExitDur);
            }
            else
            {
                Debug.LogWarning($"[HeroAnimatorFactory] {spec.slug}: no cast clip — " +
                                 "Cast trigger will no-op (param still declared).");
            }

            // ── PER-SPELL casts — Any → CastN on Cast + CastVariant==N (q/w/e/r → 1..4) ──
            // Each ability slot plays its OWN cast clip. The transition adds the CastVariant
            // gate ON TOP of the same Cast/standing conditions, so when HeroAbilities fires
            // Cast with CastVariant = slot+1 the matching state wins; absent slots (null clip
            // or no spellCastClips) simply leave the generic Cast to cover them.
            int spellStates = BuildSpellCastStates(sm, locoState, combatLocoState, actionExit, spellClips);

            // ── Victory — Any → Victory on the trigger, returns to Locomotion ──
            if (victory != null)
            {
                var vicState = sm.AddState("Victory");
                vicState.motion = victory;
                var toVic = sm.AddAnyStateTransition(vicState);
                toVic.hasExitTime = false; toVic.duration = 0.1f;
                toVic.AddCondition(AnimatorConditionMode.If, 0f, "Victory");
                AddNotDead(toVic);    // F8 4647: a wave clear must not yank a dead hero out of Death
                var vicBack = vicState.AddTransition(locoState);
                vicBack.hasExitTime = true; vicBack.exitTime = 0.95f; vicBack.duration = 0.15f;
            }

            // ── WO-285: Attack (melee combo) — Any → AttackN on Attack + Combo==N ──
            // Knight cycles a 3-swing combo (Combo 0/1/2); other classes get a single
            // Attack state. Mirrors the snappy Cast timing (WO-217). Casters mostly
            // route through Cast at runtime, but the state exists so PlayAttack always
            // animates. Returns to Locomotion after the swing.
            int attackStates = BuildAttackStates(ctrl, sm, locoState, combatLocoState, actionExit, spec);

            // ── WO-285: Hit reaction — Any → Hit on the Hit trigger, back to Loco ──
            if (hit != null)
            {
                var hitState = sm.AddState("Hit");
                hitState.motion = hit;
                // FIX 1 (owner "walk became messed up"): the 4s full-body m-ss-damage flinch pinned the
                // base layer under heavy aggro. Speed it up so a standing flinch is a fast beat (~0.37s
                // at exit 0.28 below) instead of a 4s freeze.
                hitState.speed  = 3f;
                var toHit = sm.AddAnyStateTransition(hitState);
                toHit.hasExitTime = false; toHit.duration = 0.04f;
                toHit.canTransitionToSelf = false;
                toHit.AddCondition(AnimatorConditionMode.If, 0f, "Hit");
                // FIX 1: standing-only gate (mirror the Cast state at ~:489). A MOVING hero (Speed >=
                // StandingSpeedMax) NEVER enters the full-body stagger — the base layer stays in
                // Locomotion so the legs keep walking/running; captured proof was vel=6 with
                // m-ss-damage-01 w=1.0 on baseState. Idle/near-idle still plays the clean flinch.
                toHit.AddCondition(AnimatorConditionMode.Less, StandingSpeedMax, "Speed");
                // F8 4647 (THE death-shake vector): a dead hero is pinned, so Speed==0 satisfies the
                // standing gate forever. Without this guard the killing blow's own Hit trigger — and
                // every overkill/AoE tick after it — kicked the base layer Death -> Hit -> Locomotion
                // -> Death, restarting the death clip at frame 0 each lap.
                AddNotDead(toHit);
                // Exit early (0.28 of the sped-up clip ≈ 0.37s) then return combat-aware (braced loco if
                // still InCombat) so a standing flinch snaps back cleanly instead of holding the stagger.
                AddActionReturn(hitState, locoState, combatLocoState, 0.28f, 0.1f);
            }

            // ── WO-285: Death — Any → Death on Dead==true (latched), Revive clears ─
            // Dead is a BOOL latch (canonical, WO-284): the death clip holds its last
            // frame and never flickers back to idle. Revive() sets Dead=false →
            // Death → Locomotion so a respawned hero animates normally again.
            if (death != null)
            {
                // Directional deaths (DeathDirection.Left=1 / Right=2) — topple the right way.
                // These MUST be authored before the unconditional fallback below: Unity evaluates
                // AnyState transitions in order, so the old fallback-first order swallowed every
                // directional request and always played generic Death (WO-586 felt regression).
                var builtDirs = new List<int>();
                if (BuildDirectionalDeath(sm, locoState, "DeathLeft",  deathL, 1)) builtDirs.Add(1);
                if (BuildDirectionalDeath(sm, locoState, "DeathRight", deathR, 2)) builtDirs.Add(2);
                // Extended buckets (AnimParams.DeathDirection Front=3 / Back=4) — KnightMocap package clips.
                var deathFront = LoadAnimAsset(spec.deathFrontAnimPath);
                var deathBack  = LoadAnimAsset(spec.deathBackAnimPath);
                if (BuildDirectionalDeath(sm, locoState, "DeathFront", deathFront, 3)) builtDirs.Add(3);
                if (BuildDirectionalDeath(sm, locoState, "DeathBack",  deathBack,  4)) builtDirs.Add(4);

                // Fallback comes LAST so DeathDir 0 and a direction whose optional clip is absent
                // still die, while a present directional transition wins first.
                //
                // DEATH-SHAKE ROOT CAUSE (owner felt-report 2026-08-30, build 2026.08.30.348154 —
                // "the knight dying is still shaking"). This fallback used to carry ONLY `Dead`.
                // AnyState transitions are re-evaluated EVERY frame from EVERY state, and
                // canTransitionToSelf=false only suppresses the transition whose destination IS the
                // current state. Dead and DeathDir are LATCHED for the whole death window
                // (ActorAnimator.Die -> SetInteger(DeathDir) + SetBool(Dead,true), cleared only by
                // Revive), so with DeathDir=1 the animator ping-ponged forever:
                //   in DeathLeft -> AnyState->DeathLeft is self (blocked), DeathRight/Front/Back fail
                //                   their DeathDir check, the unconditioned fallback MATCHES -> Death
                //   in Death     -> AnyState->DeathLeft matches again -> DeathLeft
                // i.e. a 0.06s crossfade loop between two death clips, each restarting at frame 0 —
                // the body twitches and the death sequence never advances. (Both orderings shake:
                // the four non-mocap controllers list the fallback FIRST and loop identically.)
                // The transform-side fixes (EnterDeathFreeze, the LateUpdate death-pin in
                // HeroHealth) could never help, because the mover here is the ANIMATOR on the child
                // body, not the root.
                // FIX: make the death transitions MUTUALLY EXCLUSIVE — the fallback additionally
                // requires DeathDir != every direction that actually got a state. Exactly one death
                // transition can be satisfied at a time, so once a death state is entered nothing
                // else fires and the clip plays to its final held frame. Coverage is unchanged: a
                // direction whose optional clip was missing has no NotEqual guard, so it still lands
                // on the fallback.
                var deathState = sm.AddState("Death");
                deathState.motion = death;
                var toDeath = sm.AddAnyStateTransition(deathState);
                toDeath.hasExitTime = false; toDeath.duration = 0.06f;
                toDeath.canTransitionToSelf = false;
                toDeath.AddCondition(AnimatorConditionMode.If, 0f, "Dead");
                foreach (int builtDir in builtDirs)
                    toDeath.AddCondition(AnimatorConditionMode.NotEqual, builtDir, "DeathDir");
                var deathRevive = deathState.AddTransition(locoState);
                deathRevive.hasExitTime = false; deathRevive.duration = 0.12f;
                deathRevive.AddCondition(AnimatorConditionMode.IfNot, 0f, "Dead");
            }

            // ── WO-285: Block — Locomotion ⇄ Block on the Block bool ───────────────
            if (block != null)
            {
                var blockState = sm.AddState("Block");
                blockState.motion = block;
                // Raise the shield from the calm loco AND (when the stance split exists) the braced
                // combat loco — otherwise a hero already in CombatLocomotion could never block.
                var blockFrom = combatLocoState != null
                    ? new[] { locoState, combatLocoState }
                    : new[] { locoState };
                foreach (var from in blockFrom)
                {
                    var toBlock = from.AddTransition(blockState);
                    toBlock.hasExitTime = false; toBlock.duration = 0.1f;
                    toBlock.AddCondition(AnimatorConditionMode.If, 0f, "Block");
                }
                // Release: while still InCombat return to the braced combat loco (added first so it
                // wins the pick), otherwise the calm loco.
                if (combatLocoState != null)
                {
                    var backCombat = blockState.AddTransition(combatLocoState);
                    backCombat.hasExitTime = false; backCombat.duration = 0.12f;
                    backCombat.AddCondition(AnimatorConditionMode.IfNot, 0f, "Block");
                    backCombat.AddCondition(AnimatorConditionMode.If, 0f, "InCombat");
                }
                var blockBack = blockState.AddTransition(locoState);
                blockBack.hasExitTime = false; blockBack.duration = 0.12f;
                blockBack.AddCondition(AnimatorConditionMode.IfNot, 0f, "Block");
            }

            // ── WO-218: Upper-Body attack layer ────────────────────────────────
            // A second Override layer (weight 1) masked to arms+torso, driven by the
            // SAME "Cast"/"Attack" triggers. Base layer keeps idle/walk/run on the
            // legs; the upper layer overrides the upper body with the attack/cast clip,
            // so the hero can swing while running. Empty default state = no override
            // when not attacking (legs+arms both come from the base layer).
            if (cast != null)
                AddUpperBodyLayer(ctrl, cast, spellClips);

            EditorUtility.SetDirty(ctrl);
            Debug.Log($"[HeroAnimatorFactory] {spec.slug} built — Locomotion({added.Count} clips)" +
                      $"{(turnStates > 0 ? $" + Turn({turnStates})" : "")}" +
                      $"{(cast != null ? " + Cast(+UpperBody)" : "")}{(spellStates > 0 ? $" + Spells({spellStates})" : "")}" +
                      $"{(attackStates > 0 ? $" + Attack({attackStates})" : "")}" +
                      $"{(hit != null ? " + Hit" : "")}{(death != null ? " + Death" : "")}{(block != null ? " + Block" : "")}" +
                      $"{(victory != null ? " + Victory" : "")} → {spec.controllerPath}");
        }

        /// <summary>
        /// WO-493 #5 / WO-497: builds the hero's Injured locomotion swap — a second 1-D
        /// blend tree on Speed (wounded idle/limp/stagger) entered when Injured==true and
        /// returned when Injured==false. Mirrors BuildOrcHumanoidController's InjuredLocomotion.
        /// The injured idle/walk/run clips come from Action/Enemies/ (retargetable Humanoid);
        /// any missing injured clip falls back to the matching healthy clip so the tree is
        /// never empty (Injured then reads identical to Locomotion — a safe no-op visually).
        /// </summary>
        private static void BuildInjuredLocomotion(AnimatorController ctrl, AnimatorStateMachine sm,
                                                   AnimatorState locoState, AnimationClip healthyIdle,
                                                   AnimationClip healthyWalk, AnimationClip healthyRun,
                                                   HeroSpec spec)
        {
            AnimationClip injIdle = LoadClip(InjuredIdleClip, InjuredRoots) ?? healthyIdle;
            AnimationClip injWalk = LoadClip(InjuredWalkClip, InjuredRoots) ?? healthyWalk;
            AnimationClip injRun  = LoadClip(InjuredRunClip,  InjuredRoots) ?? healthyRun;

            var injuredState = sm.AddState("InjuredLocomotion");
            var injTree = new BlendTree { name = "InjuredLocomotion", blendType = BlendTreeType.Simple1D,
                                          blendParameter = "Speed", useAutomaticThresholds = false };
            AssetDatabase.AddObjectToAsset(injTree, ctrl);
            injuredState.motion = injTree;

            int injChildren = 0;
            // Match the healthy thresholds (idle@0 / walk@2 / run@6, walk-feel fix — see
            // the Locomotion tree above) so the swap reads at the same Speed bands the
            // hero already feeds. Same cadence compensation for the 0.5× global playback.
            if (injIdle != null) { injTree.AddChild(injIdle, 0f); injChildren++; }
            if (injWalk != null) { injTree.AddChild(injWalk, 2f); injChildren++; }
            if (injRun  != null) { injTree.AddChild(injRun,  6f); injChildren++; }
            ApplyLocomotionCadence(injTree);
            if (injChildren == 0)
                Debug.LogWarning($"[HeroAnimatorFactory] {spec.slug}: no injured/healthy locomotion " +
                                 "clips — InjuredLocomotion state is empty.");

            // Locomotion ⇄ InjuredLocomotion on the Injured bool.
            var toInjured = locoState.AddTransition(injuredState);
            toInjured.hasExitTime = false; toInjured.duration = 0.2f;
            toInjured.AddCondition(AnimatorConditionMode.If, 0f, "Injured");
            var fromInjured = injuredState.AddTransition(locoState);
            fromInjured.hasExitTime = false; fromInjured.duration = 0.2f;
            fromInjured.AddCondition(AnimatorConditionMode.IfNot, 0f, "Injured");
        }

        /// <summary>
        /// CLEANUP 2026-07-03: this used to set per-child timeScale (walk ×2 / run ×3) PURELY to
        /// cancel HeroBodySwapper.HeroAnimSpeed's global 0.5× playback (see the old comments). Now
        /// that the global is NATURAL 1.0× (proper AccuRIG/ActorCore mocap), those multipliers would
        /// OVER-speed the locomotion (walk 2×, run 3×). Reset every child to its authored 1.0× so the
        /// mocap plays at its authored cadence. (Was: run @6 → timeScale 3, walk @2 → timeScale 2.)
        /// </summary>
        private static void ApplyLocomotionCadence(BlendTree tree)
        {
            var kids = tree.children;                    // BlendTree.children returns a copy
            for (int i = 0; i < kids.Length; i++)
            {
                kids[i].timeScale = 1f; // natural authored speed — no compensation for a global multiplier
            }
            tree.children = kids;                        // write the modified copy back
        }

        /// <summary>
        /// KnightMocap V1 (owner 2026-07-04): builds the braced in-combat locomotion tree and wires
        /// the Locomotion ⇄ CombatLocomotion flip on the InCombat bool. Returns null (no combat tree,
        /// single-tree build unchanged) unless the spec supplies a combatIdleClipOverride — so every
        /// stock hero is byte-identical. CombatLocomotion reuses the same walk/run gait; only the idle
        /// pose differs (calm standby vs sword+shield ready). Same Speed thresholds + cadence as the
        /// calm tree so the swap reads at the bands the hero already feeds.
        /// </summary>
        private static AnimatorState BuildCombatLocomotion(AnimatorController ctrl, AnimatorStateMachine sm,
                                                           AnimatorState locoState, AnimationClip walk,
                                                           AnimationClip run, HeroSpec spec)
        {
            if (string.IsNullOrEmpty(spec.combatIdleClipOverride)) return null;
            AnimationClip combatIdle = LoadClip(spec.combatIdleClipOverride, spec.searchRoots);
            if (combatIdle == null)
            {
                Debug.LogWarning($"[HeroAnimatorFactory] {spec.slug}: combat idle '{spec.combatIdleClipOverride}' " +
                                 "missing — combat-stance split skipped (single Locomotion tree).");
                return null;
            }

            // Owner picks 2026-07-11: combat gait is registry-resolvable
            // (knight.combatWalk/combatRun manual rows; miss = the spec override verbatim).
            AnimationClip combatWalk = MotionCastings.Resolve(spec.castingTarget, "combatWalk",
                !string.IsNullOrEmpty(spec.combatWalkClipOverride)
                    ? LoadClip(spec.combatWalkClipOverride, spec.searchRoots) : walk);
            AnimationClip combatRun = MotionCastings.Resolve(spec.castingTarget, "combatRun",
                !string.IsNullOrEmpty(spec.combatRunClipOverride)
                    ? LoadClip(spec.combatRunClipOverride, spec.searchRoots) : run);

            var combatLocoState = sm.AddState("CombatLocomotion");
            var cblend = new BlendTree { name = "CombatLocomotion", blendType = BlendTreeType.Simple1D,
                                         blendParameter = "Speed", useAutomaticThresholds = false };
            AssetDatabase.AddObjectToAsset(cblend, ctrl);
            combatLocoState.motion = cblend;
            cblend.AddChild(combatIdle, 0f);          // braced/ready idle
            if (combatWalk != null) cblend.AddChild(combatWalk, 2f);
            if (combatRun  != null) cblend.AddChild(combatRun,  6f);
            ApplyLocomotionCadence(cblend);
            return combatLocoState;
        }

        /// <summary>
        /// Wires calm ⇄ combat stance transitions. When <see cref="HeroSpec.unsheatheClipOverride"/>
        /// is set, a standing engage plays the draw clip before CombatLocomotion; moving engages
        /// skip straight to the braced gait (KnightPackage pattern, owner 2026-07-03).
        /// </summary>
        private static void WireCombatStanceTransitions(AnimatorStateMachine sm,
                                                      AnimatorState locoState,
                                                      AnimatorState combatLocoState,
                                                      HeroSpec spec)
        {
            if (combatLocoState == null) return;

            const float EngageSpeedMax = 0.5f;
            AnimationClip unsheathe = null;
            if (!string.IsNullOrEmpty(spec.unsheatheClipOverride))
                unsheathe = LoadClip(spec.unsheatheClipOverride, spec.searchRoots);
            // Owner pick 2026-07-11 (ActorCore sword_drawing_m): registry row wins.
            unsheathe = MotionCastings.Resolve(spec.castingTarget, "unsheathe", unsheathe);

            if (unsheathe != null)
            {
                var unsheatheState = sm.AddState("Unsheathe");
                unsheatheState.motion = unsheathe;
                unsheatheState.speed  = 1f;

                var toDraw = locoState.AddTransition(unsheatheState);
                toDraw.hasExitTime = false; toDraw.duration = 0.1f;
                toDraw.AddCondition(AnimatorConditionMode.If, 0f, "InCombat");
                toDraw.AddCondition(AnimatorConditionMode.Less, EngageSpeedMax, "Speed");

                var toCombatMoving = locoState.AddTransition(combatLocoState);
                toCombatMoving.hasExitTime = false; toCombatMoving.duration = 0.2f;
                toCombatMoving.AddCondition(AnimatorConditionMode.If, 0f, "InCombat");
                toCombatMoving.AddCondition(AnimatorConditionMode.Greater, EngageSpeedMax - 0.01f, "Speed");

                var done = unsheatheState.AddTransition(combatLocoState);
                done.hasExitTime = true; done.exitTime = 0.92f; done.duration = 0.15f;

                var abort = unsheatheState.AddTransition(locoState);
                abort.hasExitTime = false; abort.duration = 0.15f;
                abort.AddCondition(AnimatorConditionMode.IfNot, 0f, "InCombat");
            }
            else
            {
                var toCombat = locoState.AddTransition(combatLocoState);
                toCombat.hasExitTime = false; toCombat.duration = 0.25f;
                toCombat.AddCondition(AnimatorConditionMode.If, 0f, "InCombat");
            }

            var toCalm = combatLocoState.AddTransition(locoState);
            toCalm.hasExitTime = false; toCalm.duration = 0.25f;
            toCalm.AddCondition(AnimatorConditionMode.IfNot, 0f, "InCombat");
        }

        /// <summary>
        /// Combat-aware return from an action state (attack/cast/hit). When a CombatLocomotion state
        /// exists, adds a return to it gated on InCombat==true FIRST (so it wins the pick) — the hero
        /// snaps back to the braced gait after a swing mid-fight instead of flashing the calm idle —
        /// then the unconditioned return to the calm Locomotion. Stock heroes (combatLoco == null)
        /// get ONLY the calm return with the same exit timing → byte-identical to the prior build.
        /// </summary>
        private static void AddActionReturn(AnimatorState state, AnimatorState locoState,
                                            AnimatorState combatLocoState, float exitTime, float duration)
        {
            if (combatLocoState != null)
            {
                var toCombat = state.AddTransition(combatLocoState);
                toCombat.hasExitTime = true; toCombat.exitTime = exitTime; toCombat.duration = duration;
                toCombat.AddCondition(AnimatorConditionMode.If, 0f, "InCombat");
            }
            var toCalm = state.AddTransition(locoState);
            toCalm.hasExitTime = true; toCalm.exitTime = exitTime; toCalm.duration = duration;
        }

        /// <summary>True when this spec supplies any in-place turn clip (KnightMocap only). Gates both
        /// the TurnDir param declaration and the turn-state build so every stock hero stays byte-identical.</summary>
        private static bool HasTurnClips(HeroSpec spec) =>
            !string.IsNullOrEmpty(spec.turnLeftClip)    || !string.IsNullOrEmpty(spec.turnRightClip) ||
            !string.IsNullOrEmpty(spec.turnLeft180Clip) || !string.IsNullOrEmpty(spec.turnRight180Clip);

        /// <summary>
        /// TURN-IN-PLACE tier (owner 2026-07-04, KnightMocap full-turning): builds one in-place turn
        /// state per supplied clip (TurnLeft/TurnRight = 90°, TurnLeft180/TurnRight180 = about-face).
        /// Each is entered from the calm AND braced-combat locomotion trees when the hero is ~stationary
        /// (Speed &lt; <see cref="StandingSpeedMax"/>) and HeroLocomotion has driven TurnDir to that value
        /// (−1/1/−2/2). The pivot plays out, then returns combat-aware; it also early-outs the instant the
        /// hero starts translating (Speed climbs past standing) so the walk/run gait takes over and we
        /// never foot-slide on the pivot. Purely cosmetic — HeroLocomotion still owns the actual yaw
        /// (its LookRotation slerp is the sole rotation writer). Returns the number of turn states built;
        /// 0 (and no TurnDir param) for every stock hero (<see cref="HasTurnClips"/> false).
        /// </summary>
        private static int BuildTurnInPlace(AnimatorController ctrl, AnimatorStateMachine sm,
                                            AnimatorState locoState, AnimatorState combatLocoState, HeroSpec spec)
        {
            if (!HasTurnClips(spec)) return 0;

            var defs = new (string clip, int dir, string name)[]
            {
                (spec.turnLeftClip,     -1, "TurnLeft"),
                (spec.turnRightClip,     1, "TurnRight"),
                (spec.turnLeft180Clip,  -2, "TurnLeft180"),
                (spec.turnRight180Clip,  2, "TurnRight180"),
            };
            var fromStates = combatLocoState != null
                ? new[] { locoState, combatLocoState }
                : new[] { locoState };

            int built = 0;
            foreach (var d in defs)
            {
                if (string.IsNullOrEmpty(d.clip)) continue;
                var clip = LoadClip(d.clip, spec.searchRoots);
                if (clip == null) continue;

                var state = sm.AddState(d.name);
                state.motion = clip;

                // Enter from either loco tree ONLY while ~stationary and TurnDir == this value. Added
                // AFTER the combat/injured swaps so those keep priority; a pivot sets TurnDir only briefly.
                foreach (var from in fromStates)
                {
                    var to = from.AddTransition(state);
                    to.hasExitTime = false; to.duration = 0.08f;
                    to.AddCondition(AnimatorConditionMode.Less, StandingSpeedMax, "Speed");
                    to.AddCondition(AnimatorConditionMode.Equals, d.dir, "TurnDir");
                }

                // Early-out the moment the hero actually starts translating — walk/run takes over
                // (no foot-slide on the in-place pivot). Combat return added first so it wins.
                if (combatLocoState != null)
                {
                    var mv = state.AddTransition(combatLocoState);
                    mv.hasExitTime = false; mv.duration = 0.1f;
                    mv.AddCondition(AnimatorConditionMode.Greater, StandingSpeedMax, "Speed");
                    mv.AddCondition(AnimatorConditionMode.If, 0f, "InCombat");
                }
                var mvCalm = state.AddTransition(locoState);
                mvCalm.hasExitTime = false; mvCalm.duration = 0.1f;
                mvCalm.AddCondition(AnimatorConditionMode.Greater, StandingSpeedMax, "Speed");

                // Otherwise play the pivot out, then return combat-aware (braced loco if still InCombat).
                AddActionReturn(state, locoState, combatLocoState, 0.85f, 0.12f);
                built++;
            }
            return built;
        }

        /// <summary>
        /// WO-285: builds the melee Attack state(s). A single clip → one "Attack"
        /// state fired by the Attack trigger. Multiple clips (Knight combo) → one
        /// state per clip ("Attack0/1/2"), each entered when the Attack trigger fires
        /// AND Combo == that index, so PlayerAttackController cycling Combo plays a
        /// different swing each hit. Every state returns to Locomotion (snappy, WO-217).
        /// Returns the number of attack states built (0 = no clips found).
        /// </summary>
        private static int BuildAttackStates(AnimatorController ctrl, AnimatorStateMachine sm,
                                             AnimatorState locoState, AnimatorState combatLocoState,
                                             float actionExit, HeroSpec spec)
        {
            if (spec.attackClips == null || spec.attackClips.Length == 0) return 0;

            int built = 0;
            bool combo = spec.attackClips.Length > 1;
            for (int i = 0; i < spec.attackClips.Length; i++)
            {
                var clip = LoadClip(spec.attackClips[i], spec.searchRoots);
                if (clip == null) continue;

                var state = sm.AddState(combo ? $"Attack{i}" : "Attack");
                state.motion = clip;
                state.speed  = AttackSpeed;   // WO-217: snappier swing

                var toAttack = sm.AddAnyStateTransition(state);
                toAttack.hasExitTime = false; toAttack.duration = 0.05f;
                toAttack.canTransitionToSelf = false;
                toAttack.AddCondition(AnimatorConditionMode.If, 0f, "Attack");
                // WO-218: full-body melee only when standing — while moving the legs
                // stay in Locomotion and the upper-body layer carries the swing.
                toAttack.AddCondition(AnimatorConditionMode.Less, StandingSpeedMax, "Speed");
                if (combo)
                    toAttack.AddCondition(AnimatorConditionMode.Equals, i, "Combo");
                AddNotDead(toAttack);   // F8 4647: death is terminal — a corpse never swings

                AddActionReturn(state, locoState, combatLocoState, actionExit, CastExitDur);
                built++;
            }
            return built;
        }

        /// <summary>
        /// Loads (and, when <see cref="HeroSpec.castingTarget"/> is set, registry-resolves)
        /// the per-slot cast clips ONCE for both the base layer and the upper-body overlay.
        /// Keyword mapping mirrors KnightPackageControllerBuilder :318-330 EXACTLY:
        /// [1] q → skill1, [2] w → skill2, [3] e → castHeal (the heal/ward slot),
        /// [4] r → hardcoded pick (no keyword — matches the package builder).
        /// Registry miss = the spec's hardcoded pick verbatim (never a broken state); a
        /// slot whose clip is null after both is skipped by the callers, so the generic
        /// Cast covers it. Stock heroes (castingTarget null) = plain loads, byte-identical.
        /// </summary>
        private static AnimationClip[] ResolveSpellCastClips(HeroSpec spec)
        {
            if (spec.spellCastClips == null) return null;
            var clips = new AnimationClip[spec.spellCastClips.Length];
            bool wrap = !string.IsNullOrEmpty(spec.castingTarget);
            for (int v = 1; v < spec.spellCastClips.Length; v++)
            {
                var clip = string.IsNullOrEmpty(spec.spellCastClips[v])
                    ? null : LoadClip(spec.spellCastClips[v], spec.searchRoots);
                if (wrap)
                {
                    if      (v == 1) clip = MotionCastings.Resolve(spec.castingTarget, ActionKeywords.Skill1,   clip);
                    else if (v == 2) clip = MotionCastings.Resolve(spec.castingTarget, ActionKeywords.Skill2,   clip);
                    // Cast_e is the heal/ward slot (E-slot actives) — owner pick 2026-07-11:
                    // heal casts fire the Magical Moves "Magic Spell Cast 02" via the
                    // knight.castHeal registry row (melee/caster hard rule, F8-48).
                    else if (v == 3) clip = MotionCastings.Resolve(spec.castingTarget, ActionKeywords.CastHeal, clip);
                }
                clips[v] = clip;
            }
            return clips;
        }

        /// <summary>
        /// PER-SPELL casts: one Cast state per ability slot. For each non-null entry in
        /// spellClips[1..4] (resolved once by <see cref="ResolveSpellCastClips"/>) builds a
        /// "Cast_q/w/e/r" state whose Any→state transition
        /// fires on the Cast trigger AND CastVariant == that index. The generic Cast state
        /// (built by the caller, unconditioned on CastVariant) covers variant 0 and any slot
        /// without its own clip. Each state returns to Locomotion with the snappy timing.
        /// Standing-gated like the generic cast (legs keep moving via the upper-body layer).
        /// Returns the number of per-spell states built.
        /// </summary>
        private static int BuildSpellCastStates(AnimatorStateMachine sm, AnimatorState locoState,
                                                AnimatorState combatLocoState, float actionExit,
                                                AnimationClip[] spellClips)
        {
            if (spellClips == null) return 0;
            int built = 0;
            for (int v = 1; v < spellClips.Length; v++)
            {
                var clip = spellClips[v];
                if (clip == null) continue;

                var state = sm.AddState($"Cast_{CastVariantStateName(v)}");
                state.motion = clip;
                state.speed  = AttackSpeed;

                var toState = sm.AddAnyStateTransition(state);
                toState.hasExitTime = false; toState.duration = 0.05f;
                toState.canTransitionToSelf = false;
                toState.AddCondition(AnimatorConditionMode.If, 0f, "Cast");
                toState.AddCondition(AnimatorConditionMode.Equals, v, "CastVariant");
                toState.AddCondition(AnimatorConditionMode.Less, StandingSpeedMax, "Speed");
                AddNotDead(toState);   // F8 4647: death is terminal — a corpse never casts

                AddActionReturn(state, locoState, combatLocoState, actionExit, CastExitDur);
                built++;
            }
            return built;
        }

        private static bool HasAnySpellClip(AnimationClip[] spellClips)
        {
            if (spellClips == null) return false;
            for (int i = 1; i < spellClips.Length; i++)
                if (spellClips[i] != null) return true;
            return false;
        }

        private static string CastVariantStateName(int variant)
        {
            switch (variant)
            {
                case 1: return "q";
                case 2: return "w";
                case 3: return "e";
                case 4: return "r";
                default: return "ability" + variant;
            }
        }

        /// <summary>
        /// Builds one directional Death state ("DeathLeft"/"DeathRight") gated on
        /// Dead==true AND DeathDir==dirValue, returning to Locomotion when Dead clears
        /// (Revive). Null-guarded — a missing clip skips the state and the generic Death
        /// (DeathDir 0, unconditioned) still covers every direction.
        /// <para>Returns TRUE when the state was actually built — the caller uses that to add a
        /// matching <c>DeathDir != dirValue</c> guard to the generic fallback, which is what stops
        /// the two transitions ping-ponging (the 2026-08-30 death-shake; see the call site).</para>
        /// </summary>
        private static bool BuildDirectionalDeath(AnimatorStateMachine sm, AnimatorState locoState,
                                                  string name, AnimationClip clip, int dirValue)
        {
            if (clip == null) return false;
            var state = sm.AddState(name);
            state.motion = clip;
            var to = sm.AddAnyStateTransition(state);
            to.hasExitTime = false; to.duration = 0.06f;
            to.canTransitionToSelf = false;
            to.AddCondition(AnimatorConditionMode.If, 0f, "Dead");
            to.AddCondition(AnimatorConditionMode.Equals, dirValue, "DeathDir");
            var back = state.AddTransition(locoState);
            back.hasExitTime = false; back.duration = 0.12f;
            back.AddCondition(AnimatorConditionMode.IfNot, 0f, "Dead");
            return true;
        }

        /// <summary>
        /// WO-218: adds an "Upper Body" Override layer (weight 1) masked to arms +
        /// torso so the hero can attack while moving. Layer holds an empty default
        /// state (Empty) and a Cast state with the attack clip; Any→Cast on the same
        /// "Cast" trigger, then back to Empty. While not casting the upper layer sits
        /// on the empty state and contributes nothing (legs+arms = base layer).
        /// Per-spell: also builds an upper-body state per spellClips entry (the SAME
        /// registry-resolved clips the base layer uses — resolved once, lock-step), gated
        /// the same way (Cast + CastVariant==N), so a moving caster's arms play the
        /// SPECIFIC spell while the legs keep running.
        /// </summary>
        private static void AddUpperBodyLayer(AnimatorController ctrl, AnimationClip cast,
                                              AnimationClip[] spellClips)
        {
            var mask = EnsureUpperBodyMask();

            var sm = new AnimatorStateMachine { name = "Upper Body" };
            AssetDatabase.AddObjectToAsset(sm, ctrl);

            // Empty default — no override unless an attack is in progress.
            var empty = sm.AddState("Empty");
            sm.defaultState = empty;

            // Upper-body attack state — same clip, same snappy speed (WO-217).
            var upperCast = sm.AddState("CastUpper");
            upperCast.motion = cast;
            upperCast.speed  = AttackSpeed;

            var toCast = sm.AddAnyStateTransition(upperCast);
            toCast.hasExitTime = false; toCast.duration = 0.05f;
            toCast.canTransitionToSelf = false;
            toCast.AddCondition(AnimatorConditionMode.If, 0f, "Cast");
            if (HasAnySpellClip(spellClips))
                toCast.AddCondition(AnimatorConditionMode.Equals, 0f, "CastVariant");
            // F8 4647: the overlay listens to the SAME Cast/Attack triggers as the base layer, on an
            // Override layer at weight 1 masked to arms+torso. Guarding only the base layer would leave
            // a corpse's arms swinging over the held death pose. Death is terminal on BOTH layers.
            AddNotDead(toCast);

            // WO-285: the same overlay also fires on the melee Attack trigger, so a
            // Knight swing plays on the upper body while the legs keep walking/running.
            var toAttack = sm.AddAnyStateTransition(upperCast);
            toAttack.hasExitTime = false; toAttack.duration = 0.05f;
            toAttack.canTransitionToSelf = false;
            toAttack.AddCondition(AnimatorConditionMode.If, 0f, "Attack");
            AddNotDead(toAttack);

            var back = upperCast.AddTransition(empty);
            back.hasExitTime = true;
            back.exitTime = CastExitTime;
            back.duration = CastExitDur;

            // Per-spell upper-body overlays (Cast + CastVariant==N) so a moving caster's
            // arms play the specific spell. Same resolved clips as the base-layer states.
            if (spellClips != null)
            {
                for (int v = 1; v < spellClips.Length; v++)
                {
                    var clip = spellClips[v];
                    if (clip == null) continue;

                    var st = sm.AddState($"CastUpper_{CastVariantStateName(v)}");
                    st.motion = clip;
                    st.speed  = AttackSpeed;

                    var toV = sm.AddAnyStateTransition(st);
                    toV.hasExitTime = false; toV.duration = 0.05f;
                    toV.canTransitionToSelf = false;
                    toV.AddCondition(AnimatorConditionMode.If, 0f, "Cast");
                    toV.AddCondition(AnimatorConditionMode.Equals, v, "CastVariant");
                    AddNotDead(toV);

                    var vBack = st.AddTransition(empty);
                    vBack.hasExitTime = true; vBack.exitTime = CastExitTime; vBack.duration = CastExitDur;
                }
            }

            var layer = new AnimatorControllerLayer
            {
                name             = "Upper Body",
                stateMachine     = sm,
                defaultWeight    = 1f,
                blendingMode     = AnimatorLayerBlendingMode.Override,
                avatarMask       = mask,
            };
            ctrl.AddLayer(layer);
        }

        /// <summary>
        /// WO-218: creates (or rebuilds) the arms+torso AvatarMask asset. Enables
        /// every humanoid body part, then DISABLES the legs + root so the upper-body
        /// layer never fights the base layer's locomotion. Idempotent — overwrites
        /// the asset at <see cref="UpperMaskPath"/>.
        /// </summary>
        private static AvatarMask EnsureUpperBodyMask()
        {
            var mask = new AvatarMask();
            // Enable everything first…
            for (int i = 0; i < (int)AvatarMaskBodyPart.LastBodyPart; i++)
                mask.SetHumanoidBodyPartActive((AvatarMaskBodyPart)i, true);
            // …then turn off legs + root so they stay driven by the base (locomotion) layer.
            mask.SetHumanoidBodyPartActive(AvatarMaskBodyPart.Root,      false);
            mask.SetHumanoidBodyPartActive(AvatarMaskBodyPart.LeftLeg,   false);
            mask.SetHumanoidBodyPartActive(AvatarMaskBodyPart.RightLeg,  false);
            mask.SetHumanoidBodyPartActive(AvatarMaskBodyPart.LeftFootIK,  false);
            mask.SetHumanoidBodyPartActive(AvatarMaskBodyPart.RightFootIK, false);

            var maskDir = Path.GetDirectoryName(UpperMaskPath);
            if (!string.IsNullOrEmpty(maskDir) && !Directory.Exists(maskDir))
                Directory.CreateDirectory(maskDir);

            AssetDatabase.DeleteAsset(UpperMaskPath);
            AssetDatabase.CreateAsset(mask, UpperMaskPath);
            return mask;
        }

        /// <summary>Load a standalone .anim asset (package extract folder).</summary>
        private static AnimationClip LoadAnimAsset(string assetPath)
        {
            if (string.IsNullOrEmpty(assetPath)) return null;
            var clip = AssetDatabase.LoadAssetAtPath<AnimationClip>(assetPath);
            if (clip == null)
                Debug.LogWarning($"[HeroAnimatorFactory] .anim not found: {assetPath}");
            return clip;
        }

        /// <summary>Load the motion AnimationClip from an Assets/Action FBX by basename.
        /// Skips __preview__ AND bind/T-pose clips (iClone8 exports like simple_walk
        /// ship a "0_T-Pose" take alongside the real "…TempMotion" walk — we want the
        /// motion, not the bind pose). Null + warn if absent.</summary>
        private static AnimationClip LoadClip(string fbxBaseName, string[] searchRoots = null)
        {
            var roots = new List<string>();
            if (searchRoots != null) roots.AddRange(searchRoots);
            roots.Add(ActionDir);
            foreach (var root in roots)
            {
                string candidate = root + fbxBaseName + ".fbx";
                var clip = MotionClipPicker.PickBestFromFbx(candidate);
                if (clip != null) return clip;
            }
            Debug.LogWarning($"[HeroAnimatorFactory] clip FBX not found or only T-pose inside: {fbxBaseName} " +
                             $"(searched {string.Join(", ", roots)})");
            return null;
        }
    }
}
