# -*- coding: utf-8 -*-
"""AI first-draft generator for ko / zh-Hans / ar localization JSON.
NOT linguistic QA. Preserves lore proper nouns + placeholders.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EN_PATH = ROOT / "Assets/StreamingAssets/Data/Canonical/en.json"

# Lore proper nouns kept in English (per brief):
# Elarion, Keeper, Heart, Spire, Hollowed, Hollow Ones,
# Alduin the Mournful, Syndrath the Devourer, Wardens, Folk, Chord, Lantern, Withering
# Also keep hero/NPC names: Thrain, Grom, Sylas, Elara, Aldwin, Sable, SKR

KO = {
  "title.tagline": "Chord를 지켜라. Spire를 수호하라.",
  "title.tagline.legacy.bible": "Heart를 돌보라. 어둠을 막아라.",
  "title.tagline.legacy.story": "Lantern을 돌보라. 어둠을 막아라.",
  "intro.coldOpen.line1": "오래된 계곡에, 오래된 나무가 있다.",
  "intro.coldOpen.line2": "저 너머의 어둠 속에서, 느리게 스며드는 차가운 부패가 있다.",
  "intro.coldOpen.line3": "당신은 Keeper다. 이제 그 노래는 당신 것이다.",
  "tutorial.firstVillageLoad": "고향에 온 것을 환영한다, Keeper. Heart가 당신을 위해 울린다. 잠시 걸어 보라 - 노래가 무엇을 필요로 하는지 알려 줄 것이다.",
  "tutorial.firstApproachHeart": "이곳이 Elarion이다. 단상을 만져라. 수정이 당신을 기억할 것이다.",
  "tutorial.firstCrystalClaim": "Heart는 나눌 수 있는 것을 준다. 이것들을 간직하라 - 필요할 것이다.",
  "tutorial.firstBuildingUnlock": "Folk가 당신보다 훨씬 전에 이것들을 지었다. 저마다 제 방식으로 Heart를 돌본다.",
  "tutorial.firstStoreVisit": "여기서 키울 수 없는 것은 방랑자들이 가져온다. 신중히 쓰라. 동전은 느리게 모인다.",
  "tutorial.firstDefenseRun": "어둠이 우리를 알아차렸다. 동료들을 슬롯에 배치하라. 그들은 무엇을 해야 할지 안다.",
  "tutorial.firstPetPlacement": "슬롯의 정령은 방어한다. 건물의 정령은 돌본다. 둘을 동시에 할 수는 없다.",
  "tutorial.firstAbilityCastQ": "이것은 당신의 마법이지만 Heart의 선물이다. 주어진 것을 쓰라. 돌아올 수 있을 때 돌아온다.",
  "tutorial.firstFrostNovaW": "한 길이 무너질 때를 위한 것이다. 추위가 숨을 벌어 준다. 그 숨을 잘 쓰라.",
  "tutorial.firstBeaconE": "어둠이 가장 짙게 모이는 곳에 빛을 심어라. 그 안의 탑들이 더 용감히 싸울 것이다.",
  "tutorial.firstMeteorR": "이것은 깊은 마법이다. Heart가 부를 때에만 써라.",
  "tutorial.steps.1": "고향에 온 것을 환영한다, Keeper. Spire가 왕국의 마지막 노래를 품고 있다. 그것을 지켜라.",
  "tutorial.steps.2": "Hollowed가 성벽 너머의 어둠에서 온다. 그들은 빛을 끄려 한다.",
  "tutorial.steps.3": "가진 것으로 방어를 세워라. Crystal Mine으로 걸어가 - 탭하여 채집하라.",
  "tutorial.steps.4": "좋다. Workshop에서 수정을 써 방어를 강화하라.",
  "tutorial.steps.5": "준비가 되면 파도를 시작하라. 스킬을 탭하여 시전하라 - Spire가 허락할 때 마법이 돌아온다.",
  "tutorial.steps.6": "Wardens가 당신 곁에서 싸운다. 하나를 탭해 주둔지를 주어라.",
  "tutorial.steps.7": "Spire는 당신의 친절을 기억한다. 잘 돌보라, Keeper.",
  "tutorial.steps.forceField": "성벽은 Heart 자체의 빛으로 된 포스 필드를 품고 있다 - 성문에서 어른거리는 것을 보라. 빛나는 동안 Hollowed를 되돌린다. 하지만 매 타격이 그것을 얇게 만들고, 얇아진 장은 어둠을 스며들게 한다. 성벽과 성문을 고치면 빛이 힘을 유지한다.",
  "gate.firstSeen": "Heart의 빛은 아는 이에게 길을 연다. 지나가라, Keeper - 하지만 Hollow Ones가 밀어붙일 것이다. 성벽을 고치듯 성문도 고쳐라.",
  "gate.firstDestroyed": "성문이 무너졌다. 그들이 막힘없이 들어온다. 안쪽 고리를 지키고, 다음 어둠 전에 장을 수리하라.",
  "gate.firstRepaired": "빛이 당신을 기억한다. 성문이 다시 버틴다.",
  "wave.warning.ice.1": "차가운 곳에서 온다. 느리게 움직이고, 세게 문다.",
  "wave.warning.ice.2": "서리 표식의 자들이 성문에 있다. 불을 꺼뜨리지 마라.",
  "wave.warning.fire.1": "불씨에 묶인 자들이 온다. 푸른 것을 탐한다. 동쪽 길을 지켜라.",
  "wave.warning.fire.2": "진군하며 불탄다. Heart의 뿌리에 닿게 하지 마라.",
  "wave.warning.aether.1": "만들어지지 않은 것의 잔영들 - 빠르고, 반쯤만 여기 있다. 정확히 조준하라.",
  "wave.warning.aether.2": "반쪽 영혼들이 흘러든다. Heart의 끌림을 느낀다. 되돌려 보내라.",
  "wave.warning.mixed.1": "여러 혀의 파도다. 배치하기 전에 길을 읽어라.",
  "wave.warning.mixed.2": "모든 어둠에서 온다. Wardens를 믿어라.",
  "wave.warning.boss.1": "Alduin the Mournful이 이 파도의 선두에 선다. 한때 치유사였다. 강철로 맞이하라.",
  "wave.warning.boss.2": "Withering이 발판을 얻을 때 그는 돌아온다. 다시 보내라.",
  "wave.warning.apex.1": "Syndrath the Devourer가 Heart를 선회한다. 하늘 자체가 등을 돌렸다. 위를 보라, Keeper.",
  "wave.warning.apex.2": "검은 날개가 태양을 가로지른다. Devourer는 왕국이 가장 약한 곳을 사냥한다 - Heart가 부족함을 드러내지 않게 하라.",
  "heartVoice.serene.toVigilant": "노래가 바뀐다. 어둠이 성문에 있다.",
  "heartVoice.vigilant.toWarning": "한 길이 흔들린다. Heart가 당신보다 먼저 느꼈다.",
  "heartVoice.warning.toDanger": "성벽이 얇아진다. Heart가 당신을 부른다.",
  "heartVoice.danger.toCritical": "노래가 깨진다. 지켜라, Keeper - 지금 당장.",
  "heartVoice.critical.toSerene": "Heart가 가라앉는다. Folk가 다시 숨을 쉰다.",
  "heartVoice.boss": "그가 성문 안에 선다. 시간이 느려진다. 빛이 희미해진다.",
  "heartVoice.victorious": "노래가 오른다. 계곡이 버틴다.",
  "heartVoice.alt.vigilant.1": "빛이 바뀐다. 어둠이 성문에 있다.",
  "heartVoice.alt.vigilant.2": "Spire가 꿈틀한다. 경계가 시작된다.",
  "heartVoice.alt.warning.1": "한 길이 흔들린다. Chord가 당신보다 먼저 느꼈다.",
  "heartVoice.alt.warning.2": "무언가가 다른 것보다 세게 민다. 그것을 보라.",
  "heartVoice.alt.danger.1": "성벽이 얇아진다. Elarion이 당신을 부른다.",
  "heartVoice.alt.danger.2": "길이 둘이다. 손을 멈추지 마라.",
  "heartVoice.alt.critical.1": "Chord가 깨진다. 지켜라, Keeper - 지금 당장.",
  "heartVoice.alt.critical.2": "Spire가 떨린다. 무슨 수를 써서라도 전선을 지켜라.",
  "heartVoice.alt.boss.1": "그가 성문 안에 선다. 시간이 느려진다. 빛이 희미해진다.",
  "heartVoice.alt.boss.2": "Alduin the Mournful이 길을 걷는다. 강철로 맞이하라.",
  "heartVoice.alt.victorious.1": "빛이 돌아온다. 마을이 다시 숨을 쉰다.",
  "heartVoice.alt.victorious.2": "노래가 오른다. Elarion이 버틴다.",
  "heartDamage.threshold75": "수정이 깜빡인다. Heart가 첫 타격을 입었다.",
  "heartDamage.threshold50": "철 아닌 계절에 잎이 진다. 노래가 얇아졌다.",
  "heartDamage.threshold25": "껍질이 갈라진다. 버텨라, Keeper. 버텨라.",
  "heartDamage.threshold10": "노래가 거의 사라졌다. 모든 것을 써라.",
  "heartDamage.threshold0": "...",
  "heartDamage.alt.threshold75": "불꽃이 깜빡인다. Lantern이 첫 타격을 입었다.",
  "heartDamage.alt.threshold50": "철 아닌 계절에 잎이 진다. 온기가 얇아졌다.",
  "heartDamage.alt.threshold25": "껍질이 갈라진다. 버텨라, Guardian. 버텨라.",
  "heartDamage.alt.threshold10": "빛이 거의 꺼졌다. 모든 것을 써라.",
  "victory.wave.1": "그들이 물러난다. Heart가 안정된다. 한숨, 그리고 다음.",
  "victory.wave.2": "어둠이 물러난다. 동료들을 돌보라. 노래는 아직 끝나지 않았다.",
  "victory.wave.3": "길이 버틴다. Folk가 당신을 위해 촛불을 켠다.",
  "victory.boss.1": "Alduin이 Heart의 문턱에서 부서진다. Withering이 집으로 기어간다.",
  "victory.boss.2": "계곡이 노래한다. Folk가 운다. 당신은 여전히 Keeper다. 내일 다시 일이 시작된다.",
  "victory.personalBest": "당신보다 먼저 이토록 오래 버틴 이는 없다. 옛 Keepers도 고개를 끄덕였을 것이다.",
  "victory.waveCleared.1": "어둠이 물러난다 - 지금은.",
  "victory.waveCleared.2": "Chord가 버틴다. 경계가 숨을 쉰다.",
  "victory.waveCleared.3": "Folk가 당신을 위해 촛불을 켠다.",
  "victory.waveCleared.4": "길이 다시 고요하다. Wardens를 돌보라.",
  "victory.waveCleared.5": "한숨. 한순간. 다음 파도가 올 것이다.",
  "victory.waveCleared.6": "바람이 식는다. Elarion이 당신의 이름을 기억한다.",
  "defeat.1": "노래가 멈춘다. Folk가 올려다본다. 처음으로 바람이 차갑게 느껴진다.",
  "defeat.2": "Heart가 부서진다. 하지만 유대는 그렇지 않다. 다시 시작하라, Keeper - 다른 답은 없다.",
  "defeat.3": "Elarion은 필요한 곳으로 돌아올 것이다. 당신도 그럴 것이다.",
  "defeat.alt.1": "빛이 멈춘다. Folk가 올려다본다. 처음으로 바람이 차갑게 느껴진다.",
  "defeat.alt.2": "Chord가 흔들린다. 하지만 유대는 그렇지 않다. 다시 시작하라, Keeper.",
  "petCaption.aetherSprite": "(부드러운 음악적 윙윙거림)",
  "petCaption.flamePup": "(따뜻한 낑낑, 작은 종소리처럼)",
  "petCaption.iceWolf": "(낮고 신중한 숨결)",
  "petCaption.levelUp": "(길고 놀란 음)",
  "petAmbient.aetherSprite.1": "Sprite가 당신이 일하는 것을 지켜본다. 무엇을 보는지 알 수 없다.",
  "petAmbient.aetherSprite.2": "한 음을 흥얼거리다 잊는다.",
  "petAmbient.aetherSprite.3": "당신이 웃으면 더 밝게 빛난다. 당신은 아직 몰랐다.",
  "petAmbient.flamePup.1": "Pup이 또 불을 꿈꾼다. 꼬리가 꿈틀한다.",
  "petAmbient.flamePup.2": "해질녘 따뜻한 돌 위에 웅크렸다. 그때부터 움직이지 않았다.",
  "petAmbient.flamePup.3": "외풍에 이빨을 드러냈다. 외풍이 물러났다.",
  "petAmbient.iceWolf.1": "Aldwin이 과수원에서 주둥이에 얼음을 묻히고 돌아왔다. 당신은 묻지 않았다.",
  "petAmbient.iceWolf.2": "Aldwin은 소리 없이 걷는다. Hollowed가 오면 이빨을 드러내고 시선을 돌리지 않는다.",
  "petAmbient.iceWolf.3": "그의 숨은 김을 만들지 않는다. 숨 쉬는지조차 궁금하다.",
  "keeperAmbient.1": "Pup이 또 불을 꿈꾼다. 꼬리가 꿈틀한다.",
  "keeperAmbient.2": "Mine이 가득하다. Folk가 오늘 아침 문 옆에 촛불을 남겨 두었다.",
  "keeperAmbient.3": "숲에 희미하고 오래된 노래가 있다. Heart가 흥얼거린다.",
  "keeperAmbient.4": "Sprite가 내가 일하는 것을 지켜본다. 무엇을 보는지 모르겠다.",
  "keeperAmbient.5": "Folk는 나를 보지 못할 때 작업장에 빵을 남긴다. 나는 그것을 찾는다. 아직 감사하지는 않는다.",
  "keeperAmbient.6": "Aldwin이 과수원에서 주둥이에 얼음 조각을 묻히고 돌아왔다. 물었다. 그는 말하지 않았다.",
  "keeperAmbient.7": "Tower의 등불이 만 번의 아침 동안 켜져 있었다. 이제 내가 지킬 차례다.",
  "keeperAmbient.8": "어젯밤 Heart가 나를 잠들게 노래한 것 같다. 이제 그 목소리와 내 목소리가 어디서 끝나는지 알 수 없다.",
  "milestone.firstPetLevelUp": "Sprite가 더 밝게 빛난다. 어제 못 하던 것을 오늘은 할 수 있다.",
  "milestone.firstSkillUnlocked": "노래에 새 형태가 생겼다. Heart가 당신이 자는 동안 가르쳤다.",
  "milestone.firstBossKill": "Alduin이 쓰러진다. Folk는 오늘 저녁을 백 년 동안 노래할 것이다.",
  "milestone.firstStorePurchase": "방랑자가 고개를 숙인다. Folk는 세 계곡에서 당신의 이름을 알 것이다.",
  "milestone.firstBuildingUpgrade": "Workshop의 종이 더 크게 울린다. Folk가 기뻐한다.",
  "milestone.streak7Days": "일곱 아침 동안 노래를 돌보았다. 옛 Keepers는 이미 당신을 '우리 중 하나'라 불렀을 것이다.",
  "returningPlayer": "Elarion이 당신의 화덕을 따뜻하게 지켜 두었다. 다시 환영한다, Keeper.",
  "heroSelect.title": "Defenders of the Realm",
  "heroSelect.subtitle": "powered by SKR",
  "heroSelect.confirm": "경계를 이어받다",
  "heroSelect.diveVillage": "마을로 들어가기",
  "heroSelect.jumpAction": "전투에 뛰어들기",
  "hero.mage.name": "Thrain",
  "hero.mage.role": "서리직조자",
  "hero.mage.blurb": "수정 광맥의 원로 학자. 그의 지팡이는 추위를 깨워 노래한다. Thrain이 걷는 곳에서 어둠은 느려지고, 서리는 얼린 모든 이름을 기억한다.",
  "hero.knight.name": "Grom",
  "hero.knight.role": "빛의 수호자",
  "hero.knight.blurb": "손에 망치, 방패에 태양의 문장. Grom은 축복받은 강철을 돌파구로 가져간다. 그의 빛이 닿는 곳에서 Hollowed는 흔들리고 성벽은 버틴다.",
  "hero.ranger.name": "Sylas",
  "hero.ranger.role": "숲의 Warden",
  "hero.ranger.blurb": "푸른 길의 엘프. 어둠이 다가오기 훨씬 전에 바람 위로 맑은 화살을 놓는다. Sylas는 숲을 읽고, 빠른 자를 묶으며, 화살 하나하나로 전세를 뒤집는다.",
  "hero.cleric.name": "Elara",
  "hero.cleric.role": "신성한 치유사",
  "hero.cleric.blurb": "Heart 자체의 빛을 담은 그릇. Elara는 부상당한 이를 치유하고 신실한 이를 성스러운 방호로 감싼다. 상처보다 빠르게 일어나는 은총 앞에서 어둠은 오래가지 못한다.",
  "petSelect.title": "첫 Warden을 고르세요",
  "petSelect.subtitle": "정령이 당신 곁에서 경계를 걸을 것이다. 하나와 유대하라 - 당신의 친절과 전투를 알 것이다.",
  "petSelect.confirm": "이 Warden과 유대하기",
  "elementBlurb.aether": "에테르. Heart 자체의 빛, 나누고 또 나눈다. 어둠이 헐어 놓은 것을 고친다.",
  "elementBlurb.flame": "불꽃. 화덕의 오래된 반항. 따뜻한 곳으로 스며들려는 것을 태운다.",
  "elementBlurb.ice": "얼음. 노래가 따라잡을 때까지 어둠을 붙잡아 두는 인내하는 추위.",
  "resourceBlurb.crystals": "수정. Heart의 느린 선물. 넘침이 돌 사이로 스며 오르는 곳에서 캔다.",
  "resourceBlurb.coins": "동전. 아직 서 있는 계곡에서 방랑자들이 가져온 조용한 화폐. 여기서 키울 수 없는 것에 쓰라.",
  "buildingDesc.crystalMine": "Heart의 보석 수액이 돌로 스며드는 곳. 이곳의 펫이 광맥을 돌본다.",
  "buildingDesc.petHouse": "세계수의 뿌리 속 고대의 움푹한 곳. 메아리들이 전투 사이에 여기서 쉬며, 그 존재는 돌 속의 낮은 윙윙거림이다.",
  "buildingDesc.arcaneTower": "첫 Keepers가 지었다. 당신의 부름에 응답하는 수호석을 품는다.",
  "buildingDesc.farm": "Heart가 원해서 자라는 밀. 사과는 옛 여름의 맛이 난다.",
  "buildingDesc.workshop": "망치와 대장간. Folk는 Keeper가 필요한 것을 만들고 아무것도 묻지 않는다.",
  "buildingDesc.lumbermill": "제재소의 날이 Elarion의 푸른 곳이 아직 내어 주는 목재에 윙윙거린다. 그 판자가 가장 높은 성벽을 버틴다.",
  "buildingDesc.forge": "갑옷장의 불은 식지 않는다. 여기서 Folk는 생철을 Hollowed가 쉽게 물어뜯지 못하는 판금으로 두드린다.",
  "tooltip.resourceCrystals.title": "수정",
  "tooltip.resourceCrystals.body": "Heart의 느린 선물. 넘침이 돌 사이로 스며 오르는 곳에서 캔다.",
  "tooltip.resourceCoins.title": "동전",
  "tooltip.resourceCoins.body": "아직 서 있는 계곡에서 방랑자들이 가져온 조용한 화폐. 여기서 키울 수 없는 것에 쓰라.",
  "tooltip.resourceVoidshards.title": "공허 파편",
  "tooltip.resourceVoidshards.body": "Withering의 파편. 거대한 Hollow One이 쓰러진 곳에 남는다. 수호석이 그것을 마시고 강해진다.",
  "tooltip.resourceStone.title": "돌",
  "tooltip.resourceStone.body": "계곡의 오래된 뼈에서 끌어낸다. 성벽이 그 형태를 기억한다.",
  "tooltip.resourceIron.title": "철",
  "tooltip.resourceIron.body": "깊은 광맥의 차가운 금속. Folk가 어둠이 쉽게 지나지 못하는 성벽으로 벼린다.",
  "tooltip.resourceWood.title": "나무",
  "tooltip.resourceWood.body": "Heart가 아직 지키는 푸른 곳에서 쓰러진 목재. 가장 높은 성벽을 버틴다.",
  "tooltip.buttonWalls.title": "성벽",
  "tooltip.buttonWalls.body": "Folk가 Heart 둘레에 세운 경계를 올려라. 돌, 철, 나무가 더 높이 고친다.",
  "tooltip.buttonTowers.title": "탑",
  "tooltip.buttonTowers.body": "첫 Keepers가 세운 돌 Spire. 그 수호석이 어둠에 맞서 당신의 부름에 응답한다.",
  "tooltip.buttonBuild.title": "건설",
  "tooltip.buttonBuild.body": "표시된 땅을 터치해 Spire를 세우거나, 성벽을 더 높이 고쳐라. 나머지는 Folk가 한다.",
  "tooltip.buttonSettings.title": "Keeper의 장부",
  "tooltip.buttonSettings.body": "옛 이야기를 다시 듣고, 경계의 사본을 지키거나, 새 경계를 시작하라.",
  "tooltip.buttonHelp.title": "옛 가르침",
  "tooltip.buttonHelp.body": "경계를 지키는 법 - 이전 Keepers가 당신에게 말했을 것들.",
  "tooltip.buttonClan.title": "다른 계곡들",
  "tooltip.buttonClan.body": "다른 Keepers와 경계를 잇고, 명단을 돌보며, 왕국 너머로 소식을 나누라.",
  "tooltip.buttonMailbox.title": "우편함",
  "tooltip.buttonMailbox.body": "방랑자들이 가져온 쪽지. 초대 표식과 함께 당신 소식도 보내라.",
  "tooltip.buttonHouse.title": "당신의 홀",
  "tooltip.buttonHouse.body": "모은 모든 것 - 유대된 모든 정령, 세운 모든 장소.",
  "tooltip.waveTimerPill.title": "어둠이 꿈틀한다",
  "tooltip.waveTimerPill.body": "성벽 너머에 파도가 모인다. 모을 수 있는 것을 모으고 방어를 준비하라.",
  "tooltip.waveBegin.title": "파도를 부르다",
  "tooltip.waveBegin.body": "어둠을 기다리지 마라. 지금, 당신의 경계에서 맞이하라.",
  "tooltip.ability.mage.q.title": "비전 화살",
  "tooltip.ability.mage.q.body": "당신의 마법이지만 Heart의 선물이다. 주어진 것을 쓰라 - 돌아올 수 있을 때 돌아온다.",
  "tooltip.ability.mage.w.title": "서리 폭발",
  "tooltip.ability.mage.w.body": "한 길이 무너질 때를 위한 것이다. 추위가 숨을 벌어 준다. 그 숨을 잘 쓰라.",
  "tooltip.ability.mage.e.title": "치유 봉화",
  "tooltip.ability.mage.e.body": "어둠이 가장 짙게 모이는 곳에 빛을 심어라. Heart와 가까이 선 모두가 그 안에서 치유된다.",
  "tooltip.ability.mage.r.title": "운석 강타",
  "tooltip.ability.mage.r.body": "이것은 깊은 마법이다. Heart가 부를 때에만 써라.",
  "tooltip.ability.knight.q.title": "검 강타",
  "tooltip.ability.knight.q.body": "평범한 강철, 가깝고 확실하다. Heart에 아무것도 요구하지 않으며 언제나 준비되어 있다.",
  "tooltip.ability.knight.w.title": "방패 강타",
  "tooltip.ability.knight.w.body": "파도에 방패를 세워라. Hollow Ones가 흔들리고, 당신은 전선을 지킨다.",
  "tooltip.ability.knight.e.title": "용기의 깃발",
  "tooltip.ability.knight.e.body": "옛 색을 올려라. 어둠의 한 열이 선 자리에서 베인다.",
  "tooltip.ability.knight.r.title": "철의 서약",
  "tooltip.ability.knight.r.body": "Heart에 지킨 약속. 그 빛이 상처로 다시 밀려든다.",
  "tooltip.ability.ranger.q.title": "빠른 사격",
  "tooltip.ability.ranger.q.body": "멀리 놓인 맑은 화살. 대가 없고, 현은 오래 가만히 있지 않는다.",
  "tooltip.ability.ranger.w.title": "올가미 화살",
  "tooltip.ability.ranger.w.body": "Hollow One을 땅에 고정하라. 오늘 밤 Heart의 뿌리에 닿지 못할 것이다.",
  "tooltip.ability.ranger.e.title": "매의 눈",
  "tooltip.ability.ranger.e.body": "멀리, 정확히 조준하라. 한 발이 당신이 되돌리는 어둠의 무게를 싣는다.",
  "tooltip.ability.ranger.r.title": "일제 사격",
  "tooltip.ability.ranger.r.body": "모든 화살을 한꺼번에 하늘로 놓아라. 파도 위에 거센 비처럼 내려온다.",
  "movementHint.joystick": "왼쪽 아래 조이스틱을 끌어 마을을 걸어 다니세요.",
  "movementHint.tap": "땅 어디든 탭하면 영웅이 그곳으로 걸어갑니다.",
  "movementHint.both": "조이스틱을 끌어 이동하거나 - 땅을 탭해 걸어가세요.",
  "realmMap.revealHint": "Elarion 너머의 왕국이 꿈틀한다. Wayshrine - 창백한 선돌 - 을 찾아 Realm Map으로 나서라.",
  "shopkeeperPanic.1": "나리 - 적이다! 가게는 나중에!",
  "shopkeeperPanic.2": "물건은 나중, 영광은 지금! 무기를!",
  "shopkeeperPanic.3": "지금 쇼핑이라고요?! 제발 도와주세요!",
  "shopkeeperPanic.4": "동전은 이 무리에게서 우리를 구하지 못해요 - 당신의 마법이 구해요!",
  "shopkeeperPanic.5": "나리, 금전함은 봉쇄했어요! Heart로 가세요!",
  "shopkeeperPanic.6": "파도 끝나면 할인할게요, 맹세해요! 싸우세요!",
  "swap.title": "SKR로 스왑",
  "swap.inputLabel": "보내는 금액",
  "swap.outputLabel": "받는 금액",
  "swap.rateLabel": "환율",
  "swap.feeLabel": "서비스 수수료",
  "swap.networkLabel": "네트워크 수수료",
  "swap.confirm": "지금 스왑",
  "swap.poweredBy": "Powered by Jupiter Aggregator",
  "swap.statusEnter": "금액을 입력하면 환율을 볼 수 있습니다.",
  "swap.statusLoading": "환율 가져오는 중...",
  "swap.statusConnect": "스왑하려면 지갑을 연결하세요.",
  "swap.statusSigning": "승인 위해 지갑으로 보내는 중...",
  "swap.statusError": "환율을 가져오지 못했습니다. 연결을 확인하세요.",
  "swap.statusFailed": "스왑에 실패했습니다. 다시 시도하세요.",
  "feedback.title": "솔직히 알려 주세요",
  "feedback.body": "되는 것, 안 되는 것, 빠진 것을 알려 주세요. 모든 응답을 읽으며, 감사의 선물은 무엇을 쓰든 같습니다.",
  "feedback.placeholder": "무엇이 되고, 무엇이 안 되나요?",
  "feedback.send": "보내고 보상 받기",
  "feedback.reward": "한 번만: 나무 1000, 돌 1000, 철 1000이 전부 지급됩니다.",
  "feedback.store": "스토어에서 평가하기",
  "feedback.storeCaption": "별개이며, 보상은 없습니다 - 스토어는 했는지 알려 주지 않습니다.",
  "feedback.settingsSection": "피드백",
  "feedback.settingsButton": "피드백 보내기",
  "feedback.sending": "보내는 중...",
  "feedback.serviceUnavailable": "지금은 피드백 서비스에 연결할 수 없습니다. 나중에 다시 시도하세요.",
  "feedback.storeUnavailable": "이 빌드에는 스토어 링크가 설정되어 있지 않습니다.",
  "feedback.thanks": "감사합니다 - 당신의 말이 도착했습니다. 나무 1000, 돌 1000, 철 1000이 전부 창고에 추가되었습니다.",
  "feedback.alreadyClaimed": "감사합니다 - 당신의 말이 도착했습니다. 이 왕국에서는 감사가 이미 수령되어, 이번에는 추가되지 않았습니다.",
  "feedback.grantUnavailable": "감사합니다 - 당신의 말이 도착했습니다. 지금은 감사를 추가할 수 없습니다. 여전히 당신 것이며 소진되지 않았습니다.",
  "feedback.tooShort": "조금만 더 써 주세요 - 최소 {Minimum}자.",
  "feedback.noIdentity": "계정을 확인할 수 없어 아무것도 보내지지 않았습니다. 나중에 다시 시도하세요.",
  "feedback.serverRefused": "서버가 받아들이지 않았습니다. 아무것도 보내지지 않았습니다 - 다시 시도하세요.",
  "feedback.networkFailed": "서버에 연결할 수 없습니다. 메시지가 보내지지 않았습니다. 다시 시도하세요.",
  "feedback.overCapacity": "당신의 {Resource}가 창고 한도보다 {AmountOver} 많습니다. 전부 당신 것이며 그대로입니다. {Resource}로의 수확과 보상은 한도 아래로 쓸 때까지 잠시 멈춥니다.",
  "jewelerFtue.title": "보석공 해금",
  "jewelerFtue.body": "희귀 아이템을 회수했습니다.\nSable이 세공해 정제된 보석으로 만들 수 있습니다.",
  "jewelerFtue.openJeweler": "보석공 열기",
  "jewelerFtue.guidance": "보석공의 Sable에게 가져가세요.",
  "jewelerFtue.stakeChecking": "로그인한 지갑에서 활성 네이티브 SKR 스테이크를 확인 중.",
  "jewelerFtue.stakeVerified": "네이티브 SKR 스테이크 확인됨: 주간 재굴림 +1 추가.",
  "jewelerFtue.stakeVerifiedHighTier": "네이티브 SKR 스테이크 확인됨: 주간 재굴림 +1 추가. 10,000+ SKR 스테이크는 돌당 굴림 상한도 6으로 올립니다.",
  "jewelerFtue.stakeNotVerified": "네이티브 SKR 스테이크 미확인: 주간 재굴림이 추가되지 않았습니다.",
  "jewelerPolish.title": "돌을 세공하다",
  "jewelerPolish.body": "Sable이 돌을 세공하는 데 {Duration}이 필요합니다. 작업이 끝나면 안의 보석이 드러납니다.",
  "jewelerPolish.begin": "세공 시작 - {Duration}",
  "jewelerPolish.started": "Sable이 세공을 시작했습니다. 작업 대기열에서 따르세요.",
  "jewelerPolish.failed": "돌을 작업대에 올릴 수 없었습니다.",
  "jewelerPolish.noStone": "창고에 거친 돌이 없습니다.",
  "jewelerPolish.revealTitle": "보석 공개",
  "jewelerPolish.revealBody": "Sable이 {Gem}을(를) 드러냈습니다. 창고에 추가되었습니다.",
  "jewelerPolish.keep": "보석 보관",
  "settings.title": "설정",
  "settings.section.audio": "오디오",
  "settings.audio.master": "마스터",
  "settings.audio.music": "음악",
  "settings.audio.sfx": "효과음",
  "settings.audio.muteAll": "모든 오디오 음소거",
  "settings.audio.mixerUnavailable": "오디오 믹서가 아직 연결되지 않음 - 볼륨은 저장되며 연결되면 적용됩니다.",
  "settings.section.gameplay": "게임플레이",
  "settings.difficulty.easy": "쉬움",
  "settings.difficulty.normal": "보통",
  "settings.difficulty.hard": "어려움",
  "settings.difficulty.easyBlurb": "길고 차분한 건설 시간 - 파도 사이 약 10분.",
  "settings.difficulty.normalBlurb": "표준 건설 시간 - 파도 사이 약 5분.",
  "settings.difficulty.hardBlurb": "짧고 긴장된 건설 시간 - 파도 사이 약 3분.",
  "settings.section.graphics": "그래픽",
  "settings.quality.low": "낮음 30 FPS",
  "settings.quality.high": "높음 60 FPS",
  "settings.quality.desktop": "데스크톱 60 FPS",
  "settings.section.comfort": "편의",
  "settings.comfort.screenShake": "화면 흔들림",
  "settings.toggle.on": "켜짐",
  "settings.toggle.off": "꺼짐",
  "settings.section.language": "언어",
  "settings.language.systemDefault": "기기 언어",
  "settings.language.choose": "선택: {Language}",
  "settings.section.wallet": "지갑",
  "settings.wallet.connect": "지갑 연결",
  "settings.wallet.disconnect": "지갑 연결 해제",
  "settings.wallet.disconnectAddress": "{Address} 연결 해제",
  "settings.section.help": "도움말",
  "settings.help.gameGuide": "게임 가이드",
  "settings.help.help": "도움말",
  "settings.help.resetDefaults": "기본값으로 재설정",
  "settings.section.town": "당신의 마을",
  "settings.town.defenceReports": "방어 보고",
  "settings.town.defenceReportsUnread": "방어 보고 (새 소식 {UnreadCount})",
  "settings.section.legal": "법적 고지",
  "settings.legal.privacyPolicy": "개인정보 처리방침",
  "settings.legal.termsOfService": "서비스 약관",
  "settings.section.adPrivacy": "광고 개인정보",
  "settings.adPrivacy.choices": "광고 개인정보 선택",
  "settings.adPrivacy.doNotSellOn": "판매 거부: 켜짐",
  "settings.adPrivacy.doNotSellOff": "판매 거부: 꺼짐",
  "settings.section.offline": "오프라인",
  "settings.offline.ready": "오프라인 준비됨",
  "settings.offline.play": "오프라인 플레이",
  "settings.section.developer": "개발자",
  "settings.developer.panel": "개발자 패널",
  "settings.value.percent": "{Percent}%",
  "hudCollectorsTitle": "수확",
  "hudCollectorsCount": "수집기 {0}/{1} 가득 참",
  "hudCollectorsFullLine": "수집",
  "hudCollectorsNearlyLine": "{0}% - 탭",
  "hudCollectorsWaitingLine": "{0} 대기 중",
  "hudManageIdleAll": "{0} 대기",
  "hudManageIdleSome": "{0}/{1} 대기",
  "storeWordmark": "밤의 시장",
  "heroBag": "가방",
  "heroSkills": "스킬",
  "heroLoadout": "로드아웃",
  "journeyCardDungeonsSubtitle": "잊힌 곳으로 내려가라. 살아남은 것을 가지고 돌아오라.",
  "journeyCardRealmMapSubtitle": "Heart의 빛 너머의 땅을 탐험하라.",
  "journeyCardSeasonSubtitle": "지금 왕국을 빚는 도전에 맞서라.",
  "dungeonSealedHeadline": "길이 막혀 있다.",
  "raidCooldownBadge": "회복 중",
  "raidReadyBadge": "준비됨",
  "raidCooldownCardLine": "회복 중 - {0} 후 습격 가능",
  "raidReadyCardLine": "습격 준비됨",
  "raidCooldownBlocked": "이 진영은 마지막 습격에서 아직 회복 중입니다. {0} 후에 다시 공격할 수 있습니다.",
  "raidCooldownStarted": "진영은 당분간 무너져 있습니다. {0} 후 재정비합니다.",
  "raidDurationHm": "{0}시간 {1}분",
  "raidDurationM": "{0}분",
  "raidDurationSub": "1분 미만",
}

ZH = {
  "title.tagline": "守住 Chord。守卫 Spire。",
  "title.tagline.legacy.bible": "照料 Heart。挡住黑暗。",
  "title.tagline.legacy.story": "照料 Lantern。挡住黑暗。",
  "intro.coldOpen.line1": "古老山谷里，有一棵古树。",
  "intro.coldOpen.line2": "更远处的黑暗中，缓缓蔓延着冰冷腐朽。",
  "intro.coldOpen.line3": "你是 Keeper。这首歌如今属于你。",
  "tutorial.firstVillageLoad": "欢迎回家，Keeper。Heart 为你低鸣。先走走看——歌声会告诉你它需要什么。",
  "tutorial.firstApproachHeart": "这里是 Elarion。触摸台座。水晶会记住你。",
  "tutorial.firstCrystalClaim": "Heart 给出它能分出的一切。收下吧——你会用得上。",
  "tutorial.firstBuildingUnlock": "Folk 在你之前很久就建起了这些。每一座都以自己的方式照料 Heart。",
  "tutorial.firstStoreVisit": "这里种不出的，流浪者会带来。明智地花费。硬币来得慢。",
  "tutorial.firstDefenseRun": "黑暗已注意到我们。把同伴放到槽位上。他们知道该做什么。",
  "tutorial.firstPetPlacement": "槽位上的灵体负责防守。建筑旁的灵体负责照料。二者不能同时兼顾。",
  "tutorial.firstAbilityCastQ": "这是你的魔法，却是 Heart 的馈赠。用所给予的。它会在能回来时回来。",
  "tutorial.firstFrostNovaW": "当一条通路失守时用它。寒冷为你争取一息。把这一息用好。",
  "tutorial.firstBeaconE": "在黑暗最浓处种下光。其中的塔会更勇猛地战斗。",
  "tutorial.firstMeteorR": "这是深沉的魔法。只在 Heart 召唤时动用。",
  "tutorial.steps.1": "欢迎回家，Keeper。Spire 守着王国最后的歌。保护它。",
  "tutorial.steps.2": "Hollowed 从墙外黑暗而来。他们要熄灭光明。",
  "tutorial.steps.3": "用你已有的建造防御。走到 Crystal Mine——点按采集。",
  "tutorial.steps.4": "很好。在 Workshop 花费水晶升级防御。",
  "tutorial.steps.5": "准备好后开始一波进攻。点按技能施放——Spire 允许时魔法会回来。",
  "tutorial.steps.6": "Wardens 与你并肩作战。点按一名给他们驻地。",
  "tutorial.steps.7": "Spire 记得你的善意。好好照料它，Keeper。",
  "tutorial.steps.forceField": "城墙持有 Heart 自身之光构成的力场——看它在城门闪烁。发光时会把 Hollowed 挡回。但每次打击都会削弱它，薄弱的力场会让黑暗渗入。修好城墙与城门，光就能保持力量。",
  "gate.firstSeen": "Heart 之光为它所识者让路。走过去吧，Keeper——但 Hollow Ones 会推挤它。像修墙一样修门。",
  "gate.firstDestroyed": "城门已落。他们畅通无阻。守住内环，在下一波黑暗前修复力场。",
  "gate.firstRepaired": "光记得你。城门再次稳住。",
  "wave.warning.ice.1": "他们来自寒冷之地。行动缓慢，咬得极狠。",
  "wave.warning.ice.2": "霜痕者已到城门。让火继续燃烧。",
  "wave.warning.fire.1": "余烬缚者来了，饥渴于青绿之物。守住东侧通路。",
  "wave.warning.fire.2": "他们边行军边燃烧。别让他们碰到 Heart 的根。",
  "wave.warning.aether.1": "未成之物的残影——迅疾，半在此处。瞄准要准。",
  "wave.warning.aether.2": "半魂飘入。它们感到 Heart 的牵引。把它们挡回去。",
  "wave.warning.mixed.1": "众舌之潮。布置前先读懂各条通路。",
  "wave.warning.mixed.2": "他们从每一处黑暗而来。信任你的 Wardens。",
  "wave.warning.boss.1": "Alduin the Mournful 走在这潮头。他曾是医者。以钢铁迎接他。",
  "wave.warning.boss.2": "当 Withering 找到立足点，他会回来。把他送回去。",
  "wave.warning.apex.1": "Syndrath the Devourer 环绕 Heart。天空本身已背弃我们。抬头看，Keeper。",
  "wave.warning.apex.2": "黑翼掠过太阳。Devourer 猎杀王国最弱之处——别让它发现 Heart 不足。",
  "heartVoice.serene.toVigilant": "歌声转变。黑暗已到城门。",
  "heartVoice.vigilant.toWarning": "一条通路动摇。Heart 比你更早感到。",
  "heartVoice.warning.toDanger": "城墙变薄。Heart 在呼唤你。",
  "heartVoice.danger.toCritical": "歌声断裂。防守，Keeper——就在现在。",
  "heartVoice.critical.toSerene": "Heart 平静下来。Folk 再次呼吸。",
  "heartVoice.boss": "他站在门内。时间变慢。光变暗。",
  "heartVoice.victorious": "歌声升起。山谷守住了。",
  "heartVoice.alt.vigilant.1": "光转变。黑暗已到城门。",
  "heartVoice.alt.vigilant.2": "Spire 苏醒。守望开始。",
  "heartVoice.alt.warning.1": "一条通路动摇。Chord 比你更早感到。",
  "heartVoice.alt.warning.2": "有什么比其余的推得更狠。看向它。",
  "heartVoice.alt.danger.1": "城墙变薄。Elarion 在呼唤你。",
  "heartVoice.alt.danger.2": "两条通路同时告急。双手别停。",
  "heartVoice.alt.critical.1": "Chord 断裂。防守，Keeper——就在现在。",
  "heartVoice.alt.critical.2": "Spire 颤动。不惜一切守住防线。",
  "heartVoice.alt.boss.1": "他站在门内。时间变慢。光变暗。",
  "heartVoice.alt.boss.2": "Alduin the Mournful 走在通路上。以钢铁迎接他。",
  "heartVoice.alt.victorious.1": "光归来。村庄再次呼吸。",
  "heartVoice.alt.victorious.2": "歌声升起。Elarion 守住了。",
  "heartDamage.threshold75": "水晶闪烁。Heart 承受了第一击。",
  "heartDamage.threshold50": "叶子在错误的季节落下。歌声变薄了。",
  "heartDamage.threshold25": "树皮在裂开。坚持，Keeper。坚持。",
  "heartDamage.threshold10": "歌声几乎消失。倾尽一切。",
  "heartDamage.threshold0": "...",
  "heartDamage.alt.threshold75": "火焰闪烁。Lantern 承受了第一击。",
  "heartDamage.alt.threshold50": "叶子在错误的季节落下。温暖变薄了。",
  "heartDamage.alt.threshold25": "树皮在裂开。坚持，Guardian。坚持。",
  "heartDamage.alt.threshold10": "光几乎熄灭。倾尽一切。",
  "victory.wave.1": "他们退却。Heart 稳住。一息，然后下一波。",
  "victory.wave.2": "黑暗退走。照料你的同伴。歌尚未结束。",
  "victory.wave.3": "通路守住。Folk 为你点起蜡烛。",
  "victory.boss.1": "Alduin 在 Heart 门槛处碎裂。Withering 爬回老家。",
  "victory.boss.2": "山谷歌唱。Folk 落泪。你仍是 Keeper。明日工作再起。",
  "victory.personalBest": "此前无人守得如此之久。旧日 Keepers 会点头认可。",
  "victory.waveCleared.1": "黑暗退走——暂时如此。",
  "victory.waveCleared.2": "Chord 守住。守望得以喘息。",
  "victory.waveCleared.3": "Folk 为你点起蜡烛。",
  "victory.waveCleared.4": "通路再次安静。照料你的 Wardens。",
  "victory.waveCleared.5": "一息。一瞬。下一潮会来。",
  "victory.waveCleared.6": "风凉了。Elarion 记得你的名字。",
  "defeat.1": "歌声停止。Folk 抬头。风第一次显得寒冷。",
  "defeat.2": "Heart 碎裂。但羁绊未断。重新开始，Keeper——没有别的答案。",
  "defeat.3": "Elarion 会回到需要它的地方。你也会。",
  "defeat.alt.1": "光停止。Folk 抬头。风第一次显得寒冷。",
  "defeat.alt.2": "Chord 动摇。但羁绊未断。重新开始，Keeper。",
  "petCaption.aetherSprite": "（柔和的乐音嗡鸣）",
  "petCaption.flamePup": "（温暖的轻吠，像小铃）",
  "petCaption.iceWolf": "（低沉、斟酌的呼吸）",
  "petCaption.levelUp": "（悠长而惊讶的音符）",
  "petAmbient.aetherSprite.1": "Sprite 看着你工作。你不知道它看见了什么。",
  "petAmbient.aetherSprite.2": "它哼出一个音，然后忘掉。",
  "petAmbient.aetherSprite.3": "你笑时它更亮。你还不知道。",
  "petAmbient.flamePup.1": "Pup 又在梦见火。尾巴抽动。",
  "petAmbient.flamePup.2": "日落时它蜷在温石上。此后再没动过。",
  "petAmbient.flamePup.3": "它朝一阵穿堂风龇牙。风退了。",
  "petAmbient.iceWolf.1": "Aldwin 从果园回来，鼻口带着冰。你没有问。",
  "petAmbient.iceWolf.2": "Aldwin 无声踱步。Hollowed 来时，它龇牙，目光不移。",
  "petAmbient.iceWolf.3": "它的呼吸不起白雾。你怀疑它是否在呼吸。",
  "keeperAmbient.1": "Pup 又在梦见火。尾巴抽动。",
  "keeperAmbient.2": "Mine 已满。Folk 今早在门旁留了一支蜡烛。",
  "keeperAmbient.3": "林中有一首微弱而古老的歌。Heart 在低鸣。",
  "keeperAmbient.4": "Sprite 看着我工作。我不知道它看见了什么。",
  "keeperAmbient.5": "Folk 在看不见我时把面包放在工坊。我找到了。我还没感谢他们。",
  "keeperAmbient.6": "Aldwin 从果园回来，鼻口带着一小片冰。我问了。它没说。",
  "keeperAmbient.7": "Tower 的灯已亮过一万个清晨。轮到我守它了。",
  "keeperAmbient.8": "我想昨夜 Heart 把我唱入了睡眠。我已分不清它的声音在何处结束、我的从何处开始。",
  "milestone.firstPetLevelUp": "Sprite 更亮了。昨天做不到的，今天能做到。",
  "milestone.firstSkillUnlocked": "歌中有了新的形状。Heart 在你沉睡时教会了它。",
  "milestone.firstBossKill": "Alduin 倒下。Folk 会把今晚唱上一百年。",
  "milestone.firstStorePurchase": "流浪者鞠躬。Folk 会在三个山谷知道你的名字。",
  "milestone.firstBuildingUpgrade": "Workshop 的铃更响了。Folk 很高兴。",
  "milestone.streak7Days": "七个清晨照料这首歌。旧日 Keepers 此刻会称你为“我们自己人”。",
  "returningPlayer": "Elarion 为你留着温暖炉火。欢迎回来，Keeper。",
  "heroSelect.title": "Defenders of the Realm",
  "heroSelect.subtitle": "powered by SKR",
  "heroSelect.confirm": "接过守望",
  "heroSelect.diveVillage": "进入村庄",
  "heroSelect.jumpAction": "投入战斗",
  "hero.mage.name": "Thrain",
  "hero.mage.role": "织霜者",
  "hero.mage.blurb": "水晶矿脉的长老学者，他的法杖唤醒寒冷之歌。Thrain 所到之处，黑暗变缓，霜记住它冻结的每一个名字。",
  "hero.knight.name": "Grom",
  "hero.knight.role": "持光者",
  "hero.knight.blurb": "手持战锤，盾上绘着太阳徽记，Grom 带着受祝福的钢铁冲入缺口。他的光所及之处，Hollowed 动摇，城墙稳住。",
  "hero.ranger.name": "Sylas",
  "hero.ranger.role": "林木 Warden",
  "hero.ranger.blurb": "青绿小径上的精灵，在黑暗靠近之前就将利箭放上风。Sylas 读懂林木，困住迅疾者，一箭一箭扭转战局。",
  "hero.cleric.name": "Elara",
  "hero.cleric.role": "神圣医者",
  "hero.cleric.blurb": "Heart 自身之光的器皿，Elara 治愈伤者，以圣护裹住忠信者。黑暗无法胜过升起比它造成的伤更快的恩典。",
  "petSelect.title": "选择你的第一位 Warden",
  "petSelect.subtitle": "一位灵体会与你并肩守望。与之一结缘——它会知晓你的善意与你的战斗。",
  "petSelect.confirm": "与这位 Warden 结缘",
  "elementBlurb.aether": "以太。Heart 自身之光，分享再分享。修补黑暗撕开的裂痕。",
  "elementBlurb.flame": "火焰。炉火古老的反抗。烧掉企图潜入温暖之处的事物。",
  "elementBlurb.ice": "冰。耐心的寒冷，把黑暗按住，直到歌声赶上。",
  "resourceBlurb.crystals": "水晶。Heart 缓慢的馈赠。在其溢出渗入石中之处开采。",
  "resourceBlurb.coins": "硬币。流浪者从仍屹立的山谷带来的安静通货。花在这里种不出的东西上。",
  "buildingDesc.crystalMine": "Heart 的宝石液渗入石中之处。此处的宠物照料矿脉。",
  "buildingDesc.petHouse": "世界树根中的古老凹处。回声在战斗之间在此歇息，它们的存在是石中低沉的嗡鸣。",
  "buildingDesc.arcaneTower": "由第一代 Keepers 建造。持有回应你召唤的守护石。",
  "buildingDesc.farm": "因 Heart 所愿而生长的麦。苹果有旧日夏日的味道。",
  "buildingDesc.workshop": "锤与炉。Folk 做出 Keeper 所需，不问回报。",
  "buildingDesc.lumbermill": "锯木场的刀刃嗡鸣着切割 Elarion 青绿之地仍愿给出的木材。其木板撑起最高的城墙。",
  "buildingDesc.forge": "盔甲匠的火永不熄。Folk 在此把生铁锤成 Hollowed 难以咬穿的甲片。",
  "tooltip.resourceCrystals.title": "水晶",
  "tooltip.resourceCrystals.body": "Heart 缓慢的馈赠。在其溢出渗入石中之处开采。",
  "tooltip.resourceCoins.title": "硬币",
  "tooltip.resourceCoins.body": "流浪者从仍屹立的山谷带来的安静通货。花在这里种不出的东西上。",
  "tooltip.resourceVoidshards.title": "虚空碎片",
  "tooltip.resourceVoidshards.body": "Withering 的碎片，留在强大 Hollow One 倒下之处。守护石饮下它们并变强。",
  "tooltip.resourceStone.title": "石料",
  "tooltip.resourceStone.body": "取自山谷古老的骨骼。城墙记得它的形状。",
  "tooltip.resourceIron.title": "铁",
  "tooltip.resourceIron.body": "深矿脉的冷金属。Folk 将其锻成黑暗难以轻易穿过的墙。",
  "tooltip.resourceWood.title": "木材",
  "tooltip.resourceWood.body": "来自 Heart 仍守护的青绿之地的倒木。它撑起最高的城墙。",
  "tooltip.buttonWalls.title": "城墙",
  "tooltip.buttonWalls.body": "升起 Folk 在 Heart 周围建造的防线。石、铁与木把它修得更高。",
  "tooltip.buttonTowers.title": "塔楼",
  "tooltip.buttonTowers.body": "第一代 Keepers 升起的石质 Spire。它们的守护石回应你对黑暗的召唤。",
  "tooltip.buttonBuild.title": "建造",
  "tooltip.buttonBuild.body": "触摸标记的地面升起 Spire，或把墙修得更高。其余由 Folk 完成。",
  "tooltip.buttonSettings.title": "Keeper 的账册",
  "tooltip.buttonSettings.body": "再听一遍旧故事，保存你守望的副本，或开始新的守望。",
  "tooltip.buttonHelp.title": "旧日教诲",
  "tooltip.buttonHelp.body": "如何守望——前代 Keepers 会告诉你的事。",
  "tooltip.buttonClan.title": "其他山谷",
  "tooltip.buttonClan.body": "将你的守望与其他 Keepers 相连，照料名册，并在王国间互通消息。",
  "tooltip.buttonMailbox.title": "信箱",
  "tooltip.buttonMailbox.body": "流浪者带来的字条。用你的邀请印记送出自己的消息。",
  "tooltip.buttonHouse.title": "你的大厅",
  "tooltip.buttonHouse.body": "你收集的一切——每一只结缘的灵体，每一处升起的地方。",
  "tooltip.waveTimerPill.title": "黑暗搅动",
  "tooltip.waveTimerPill.body": "墙外潮汐聚集。尽量收集并准备防御。",
  "tooltip.waveBegin.title": "召唤浪潮",
  "tooltip.waveBegin.body": "别等黑暗。现在就在你的守望上迎战。",
  "tooltip.ability.mage.q.title": "奥术箭",
  "tooltip.ability.mage.q.body": "你的魔法，却是 Heart 的馈赠。用所给予的——它会在能回来时回来。",
  "tooltip.ability.mage.w.title": "霜爆",
  "tooltip.ability.mage.w.body": "当一条通路失守时用它。寒冷为你争取一息。把这一息用好。",
  "tooltip.ability.mage.e.title": "治愈灯塔",
  "tooltip.ability.mage.e.body": "在黑暗最浓处种下光。Heart 与附近所有人都会在其中愈合。",
  "tooltip.ability.mage.r.title": "陨石打击",
  "tooltip.ability.mage.r.body": "这是深沉的魔法。只在 Heart 召唤时动用。",
  "tooltip.ability.knight.q.title": "剑击",
  "tooltip.ability.knight.q.body": "朴素钢铁，近身而稳。它不向 Heart 索取，随时就绪。",
  "tooltip.ability.knight.w.title": "盾击",
  "tooltip.ability.knight.w.body": "以盾抵挡潮汐。Hollow Ones 动摇，你守住防线。",
  "tooltip.ability.knight.e.title": "勇毅旗帜",
  "tooltip.ability.knight.e.body": "升起旧日旗帜。一整列黑暗就地被斩断。",
  "tooltip.ability.knight.r.title": "铁之誓约",
  "tooltip.ability.knight.r.body": "对 Heart 守住的承诺。它的光涌回伤口。",
  "tooltip.ability.ranger.q.title": "速射",
  "tooltip.ability.ranger.q.body": "一支放得长远的利箭。不费代价，弓弦也不会久静。",
  "tooltip.ability.ranger.w.title": "陷阱箭",
  "tooltip.ability.ranger.w.body": "把 Hollow One 钉在地上。今夜它到不了 Heart 的根。",
  "tooltip.ability.ranger.e.title": "鹰眼",
  "tooltip.ability.ranger.e.body": "瞄得又远又准。一箭承载你挡回的黑暗之重。",
  "tooltip.ability.ranger.r.title": "齐射",
  "tooltip.ability.ranger.r.body": "把每一支箭同时放向天空。它们如暴雨砸向潮汐。",
  "movementHint.joystick": "拖动左下角摇杆在村庄中行走。",
  "movementHint.tap": "点按地面任意处，英雄会走到那里。",
  "movementHint.both": "拖动摇杆移动——或点按地面前往某处。",
  "realmMap.revealHint": "Elarion 之外的王国在搅动。拜访 Wayshrine——那块苍白立石——启程进入 Realm Map。",
  "shopkeeperPanic.1": "大人——敌人！店铺可以等等！",
  "shopkeeperPanic.2": "货以后再说，荣耀在此刻！拿起武器！",
  "shopkeeperPanic.3": "你现在还想购物？！求你帮帮我们！",
  "shopkeeperPanic.4": "硬币救不了我们——你的魔法可以！",
  "shopkeeperPanic.5": "大人，钱柜已封好！快去 Heart！",
  "shopkeeperPanic.6": "这波过后再打折，我发誓！快打！",
  "swap.title": "兑换为 SKR",
  "swap.inputLabel": "你发送",
  "swap.outputLabel": "你收到",
  "swap.rateLabel": "汇率",
  "swap.feeLabel": "服务费",
  "swap.networkLabel": "网络费",
  "swap.confirm": "立即兑换",
  "swap.poweredBy": "Powered by Jupiter Aggregator",
  "swap.statusEnter": "输入金额以查看汇率。",
  "swap.statusLoading": "正在获取汇率...",
  "swap.statusConnect": "连接钱包以兑换。",
  "swap.statusSigning": "正在发送至钱包以供批准...",
  "swap.statusError": "无法获取汇率。请检查连接。",
  "swap.statusFailed": "兑换失败。请重试。",
  "feedback.title": "请如实告诉我们",
  "feedback.body": "告诉我们哪些有效、哪些无效、还缺什么。我们会阅读每一条回复，无论写什么，感谢礼都一样。",
  "feedback.placeholder": "什么有效，什么无效？",
  "feedback.send": "发送并领取",
  "feedback.reward": "仅一次：1000 木材、1000 石料与 1000 铁，全额送达。",
  "feedback.store": "在商店评分",
  "feedback.storeCaption": "这是分开的，且没有任何奖励——商店也不会告诉我们你是否评分。",
  "feedback.settingsSection": "反馈",
  "feedback.settingsButton": "发送反馈",
  "feedback.sending": "发送中...",
  "feedback.serviceUnavailable": "暂时无法连接反馈服务。请稍后再试。",
  "feedback.storeUnavailable": "此构建未配置商店链接。",
  "feedback.thanks": "谢谢——我们已收到你的话。1000 木材、1000 石料与 1000 铁已全额加入你的仓库。",
  "feedback.alreadyClaimed": "谢谢——我们已收到你的话。此王国上感谢礼已领取，因此本次未再添加。",
  "feedback.grantUnavailable": "谢谢——我们已收到你的话。感谢礼此刻无法添加；它仍欠着你，并未用尽。",
  "feedback.tooShort": "请再多写几句——至少 {Minimum} 个字符。",
  "feedback.noIdentity": "无法验证你的账户，因此未发送任何内容。请稍后再试。",
  "feedback.serverRefused": "服务器未接受。未发送任何内容——请重试。",
  "feedback.networkFailed": "无法连接服务器。你的话未发送；请重试。",
  "feedback.overCapacity": "你的 {Resource} 现已超出仓库容量 {AmountOver}。全部仍归你所有；进入 {Resource} 的收获与奖励会暂停，直到你花费回容量以下。",
  "jewelerFtue.title": "珠宝匠已解锁",
  "jewelerFtue.body": "回收到一件稀有物品。\nSable 可将其打磨成精炼宝石。",
  "jewelerFtue.openJeweler": "打开珠宝匠",
  "jewelerFtue.guidance": "把它带给珠宝匠处的 Sable。",
  "jewelerFtue.stakeChecking": "正在检查已登录钱包是否有活跃的原生 SKR 质押。",
  "jewelerFtue.stakeVerified": "原生 SKR 质押已验证：已添加 +1 每周重掷。",
  "jewelerFtue.stakeVerifiedHighTier": "原生 SKR 质押已验证：已添加 +1 每周重掷。你的 10,000+ SKR 质押还将每石掷数上限提升至 6。",
  "jewelerFtue.stakeNotVerified": "原生 SKR 质押未验证：未添加每周重掷。",
  "jewelerPolish.title": "打磨原石",
  "jewelerPolish.body": "Sable 需要 {Duration} 打磨原石。完成后将揭示其中的宝石。",
  "jewelerPolish.begin": "开始打磨 - {Duration}",
  "jewelerPolish.started": "Sable 已开始打磨。在工作队列中跟踪。",
  "jewelerPolish.failed": "无法将原石放上工作台。",
  "jewelerPolish.noStone": "你的库房中没有粗糙原石。",
  "jewelerPolish.revealTitle": "宝石揭示",
  "jewelerPolish.revealBody": "Sable 揭示了 {Gem}。已加入你的库房。",
  "jewelerPolish.keep": "保留宝石",
  "settings.title": "设置",
  "settings.section.audio": "音频",
  "settings.audio.master": "主音量",
  "settings.audio.music": "音乐",
  "settings.audio.sfx": "音效",
  "settings.audio.muteAll": "静音全部音频",
  "settings.audio.mixerUnavailable": "音频混音器尚未接入——音量会保存，接入后生效。",
  "settings.section.gameplay": "玩法",
  "settings.difficulty.easy": "简单",
  "settings.difficulty.normal": "普通",
  "settings.difficulty.hard": "困难",
  "settings.difficulty.easyBlurb": "漫长平静的建造窗口——波次间隔约 10 分钟。",
  "settings.difficulty.normalBlurb": "标准建造窗口——波次间隔约 5 分钟。",
  "settings.difficulty.hardBlurb": "短暂紧张的建造窗口——波次间隔约 3 分钟。",
  "settings.section.graphics": "图形",
  "settings.quality.low": "低 30 FPS",
  "settings.quality.high": "高 60 FPS",
  "settings.quality.desktop": "桌面 60 FPS",
  "settings.section.comfort": "舒适",
  "settings.comfort.screenShake": "屏幕震动",
  "settings.toggle.on": "开",
  "settings.toggle.off": "关",
  "settings.section.language": "语言",
  "settings.language.systemDefault": "设备语言",
  "settings.language.choose": "选择：{Language}",
  "settings.section.wallet": "钱包",
  "settings.wallet.connect": "连接钱包",
  "settings.wallet.disconnect": "断开钱包",
  "settings.wallet.disconnectAddress": "断开 {Address}",
  "settings.section.help": "帮助",
  "settings.help.gameGuide": "游戏指南",
  "settings.help.help": "帮助",
  "settings.help.resetDefaults": "恢复默认",
  "settings.section.town": "你的城镇",
  "settings.town.defenceReports": "防御报告",
  "settings.town.defenceReportsUnread": "防御报告（{UnreadCount} 条新）",
  "settings.section.legal": "法律",
  "settings.legal.privacyPolicy": "隐私政策",
  "settings.legal.termsOfService": "服务条款",
  "settings.section.adPrivacy": "广告隐私",
  "settings.adPrivacy.choices": "广告隐私选项",
  "settings.adPrivacy.doNotSellOn": "请勿出售：开",
  "settings.adPrivacy.doNotSellOff": "请勿出售：关",
  "settings.section.offline": "离线",
  "settings.offline.ready": "离线就绪",
  "settings.offline.play": "离线游玩",
  "settings.section.developer": "开发者",
  "settings.developer.panel": "开发面板",
  "settings.value.percent": "{Percent}%",
  "hudCollectorsTitle": "收获",
  "hudCollectorsCount": "采集器 {0}/{1} 已满",
  "hudCollectorsFullLine": "收集",
  "hudCollectorsNearlyLine": "{0}% - 点按",
  "hudCollectorsWaitingLine": "{0} 等待中",
  "hudManageIdleAll": "{0} 空闲",
  "hudManageIdleSome": "{0}/{1} 空闲",
  "storeWordmark": "夜市",
  "heroBag": "背包",
  "heroSkills": "技能",
  "heroLoadout": "配装",
  "journeyCardDungeonsSubtitle": "深入被遗忘之地。带着幸存之物归来。",
  "journeyCardRealmMapSubtitle": "探索 Heart 之光以外的土地。",
  "journeyCardSeasonSubtitle": "面对此刻塑造王国的挑战。",
  "dungeonSealedHeadline": "此路已封。",
  "raidCooldownBadge": "恢复中",
  "raidReadyBadge": "就绪",
  "raidCooldownCardLine": "恢复中 - {0} 后可突袭",
  "raidReadyCardLine": "可突袭",
  "raidCooldownBlocked": "该营地仍在从你上次突袭中恢复。你可以在 {0} 后再进攻。",
  "raidCooldownStarted": "营地暂时被击溃。它将在 {0} 后重整。",
  "raidDurationHm": "{0}小时 {1}分",
  "raidDurationM": "{0}分",
  "raidDurationSub": "不到一分钟",
}


def _placeholder_tokens(s: str) -> list[str]:
    import re
    return re.findall(r"\{[^{}]+\}", s)


def build_locale(en: dict, translations: dict, locale: str) -> dict:
    out: dict = {}
    out["_comment"] = (
        f"AI FIRST DRAFT ({locale}) for multi-model review — NOT linguistic QA. "
        "Generated 2026-09-08."
    )
    if "_sources" in en:
        out["_sources"] = en["_sources"]
    missing = []
    for key, val in en.items():
        if key in ("_comment", "_sources"):
            continue
        if key not in translations:
            missing.append(key)
            continue
        t = translations[key]
        if _placeholder_tokens(val) != _placeholder_tokens(t):
            raise SystemExit(
                f"PLACEHOLDER MISMATCH {locale} {key}: "
                f"en={_placeholder_tokens(val)} vs {_placeholder_tokens(t)}"
            )
        out[key] = t
    if missing:
        raise SystemExit(f"{locale} missing {len(missing)} keys: {missing[:10]}")
    extra = set(translations) - {k for k in en if k not in ("_comment", "_sources")}
    if extra:
        raise SystemExit(f"{locale} has {len(extra)} extra keys: {sorted(extra)[:10]}")
    return out


def write_dual(locale: str, payload: dict) -> None:
    text = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    paths = [
        ROOT / f"Assets/StreamingAssets/Data/Canonical/{locale}.json",
        ROOT / f"Assets/Resources/Data/Canonical/{locale}.json",
    ]
    for p in paths:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
    a, b = (p.read_bytes() for p in paths)
    if a != b:
        raise SystemExit(f"{locale}: dual copies not byte-identical")
    print(f"OK {locale}: {len(payload)} entries -> {paths[0].name} (dual-copy)")


def main() -> None:
    from _gen_ar_dict import AR

    en = json.loads(EN_PATH.read_text(encoding="utf-8"))
    for locale, table in (("ko", KO), ("zh-Hans", ZH), ("ar", AR)):
        payload = build_locale(en, table, locale)
        write_dual(locale, payload)
        en_keys = set(en)
        out_keys = set(payload)
        if en_keys - {"_comment"} != out_keys - {"_comment"} and en_keys != out_keys:
            # both must have identical key sets including _comment/_sources shape
            pass
        if set(en.keys()) != set(payload.keys()):
            # _comment rewritten; keys must still match 1:1
            only_en = set(en) - set(payload)
            only_out = set(payload) - set(en)
            raise SystemExit(f"{locale} key parity fail en-only={only_en} out-only={only_out}")
        print(f"PARITY OK {locale}: {len(payload)} keys")


if __name__ == "__main__":
    main()
